// Code generated by MockGen. DO NOT EDIT.
// Source: domain/repo/auth.go
//
// Generated by this command:
//
//	mockgen -source domain/repo/auth.go -destination mock/auth.go -package mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	entity "github.com/icchon/matcha/api/internal/domain/entity"
	repo "github.com/icchon/matcha/api/internal/domain/repo"
	gomock "go.uber.org/mock/gomock"
)

// MockAuthQueryRepository is a mock of AuthQueryRepository interface.
type MockAuthQueryRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAuthQueryRepositoryMockRecorder
	isgomock struct{}
}

// MockAuthQueryRepositoryMockRecorder is the mock recorder for MockAuthQueryRepository.
type MockAuthQueryRepositoryMockRecorder struct {
	mock *MockAuthQueryRepository
}

// NewMockAuthQueryRepository creates a new mock instance.
func NewMockAuthQueryRepository(ctrl *gomock.Controller) *MockAuthQueryRepository {
	mock := &MockAuthQueryRepository{ctrl: ctrl}
	mock.recorder = &MockAuthQueryRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthQueryRepository) EXPECT() *MockAuthQueryRepositoryMockRecorder {
	return m.recorder
}

// Find mocks base method.
func (m *MockAuthQueryRepository) Find(ctx context.Context, userID uuid.UUID, provider entity.AuthProvider) (*entity.Auth, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, userID, provider)
	ret0, _ := ret[0].(*entity.Auth)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockAuthQueryRepositoryMockRecorder) Find(ctx, userID, provider any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockAuthQueryRepository)(nil).Find), ctx, userID, provider)
}

// Query mocks base method.
func (m *MockAuthQueryRepository) Query(ctx context.Context, q *repo.AuthQuery) ([]*entity.Auth, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Query", ctx, q)
	ret0, _ := ret[0].([]*entity.Auth)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Query indicates an expected call of Query.
func (mr *MockAuthQueryRepositoryMockRecorder) Query(ctx, q any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Query", reflect.TypeOf((*MockAuthQueryRepository)(nil).Query), ctx, q)
}

// MockAuthCommandRepository is a mock of AuthCommandRepository interface.
type MockAuthCommandRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAuthCommandRepositoryMockRecorder
	isgomock struct{}
}

// MockAuthCommandRepositoryMockRecorder is the mock recorder for MockAuthCommandRepository.
type MockAuthCommandRepositoryMockRecorder struct {
	mock *MockAuthCommandRepository
}

// NewMockAuthCommandRepository creates a new mock instance.
func NewMockAuthCommandRepository(ctrl *gomock.Controller) *MockAuthCommandRepository {
	mock := &MockAuthCommandRepository{ctrl: ctrl}
	mock.recorder = &MockAuthCommandRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthCommandRepository) EXPECT() *MockAuthCommandRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockAuthCommandRepository) Create(ctx context.Context, auth *entity.Auth) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, auth)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockAuthCommandRepositoryMockRecorder) Create(ctx, auth any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockAuthCommandRepository)(nil).Create), ctx, auth)
}

// Delete mocks base method.
func (m *MockAuthCommandRepository) Delete(ctx context.Context, userID uuid.UUID, provider entity.AuthProvider) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, userID, provider)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockAuthCommandRepositoryMockRecorder) Delete(ctx, userID, provider any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockAuthCommandRepository)(nil).Delete), ctx, userID, provider)
}

// Update mocks base method.
func (m *MockAuthCommandRepository) Update(ctx context.Context, auth *entity.Auth) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, auth)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockAuthCommandRepositoryMockRecorder) Update(ctx, auth any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockAuthCommandRepository)(nil).Update), ctx, auth)
}

// MockAuthRepository is a mock of AuthRepository interface.
type MockAuthRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAuthRepositoryMockRecorder
	isgomock struct{}
}

// MockAuthRepositoryMockRecorder is the mock recorder for MockAuthRepository.
type MockAuthRepositoryMockRecorder struct {
	mock *MockAuthRepository
}

// NewMockAuthRepository creates a new mock instance.
func NewMockAuthRepository(ctrl *gomock.Controller) *MockAuthRepository {
	mock := &MockAuthRepository{ctrl: ctrl}
	mock.recorder = &MockAuthRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthRepository) EXPECT() *MockAuthRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockAuthRepository) Create(ctx context.Context, auth *entity.Auth) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, auth)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockAuthRepositoryMockRecorder) Create(ctx, auth any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockAuthRepository)(nil).Create), ctx, auth)
}

// Delete mocks base method.
func (m *MockAuthRepository) Delete(ctx context.Context, userID uuid.UUID, provider entity.AuthProvider) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, userID, provider)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockAuthRepositoryMockRecorder) Delete(ctx, userID, provider any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockAuthRepository)(nil).Delete), ctx, userID, provider)
}

// Find mocks base method.
func (m *MockAuthRepository) Find(ctx context.Context, userID uuid.UUID, provider entity.AuthProvider) (*entity.Auth, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, userID, provider)
	ret0, _ := ret[0].(*entity.Auth)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockAuthRepositoryMockRecorder) Find(ctx, userID, provider any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockAuthRepository)(nil).Find), ctx, userID, provider)
}

// Query mocks base method.
func (m *MockAuthRepository) Query(ctx context.Context, q *repo.AuthQuery) ([]*entity.Auth, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Query", ctx, q)
	ret0, _ := ret[0].([]*entity.Auth)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Query indicates an expected call of Query.
func (mr *MockAuthRepositoryMockRecorder) Query(ctx, q any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Query", reflect.TypeOf((*MockAuthRepository)(nil).Query), ctx, q)
}

// Update mocks base method.
func (m *MockAuthRepository) Update(ctx context.Context, auth *entity.Auth) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, auth)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockAuthRepositoryMockRecorder) Update(ctx, auth any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockAuthRepository)(nil).Update), ctx, auth)
}
