// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/service/auth.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/service/auth.go -destination=internal/mock/auth_service.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	entity "github.com/icchon/matcha/api/internal/domain/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockAuthService is a mock of AuthService interface.
type MockAuthService struct {
	ctrl     *gomock.Controller
	recorder *MockAuthServiceMockRecorder
	isgomock struct{}
}

// MockAuthServiceMockRecorder is the mock recorder for MockAuthService.
type MockAuthServiceMockRecorder struct {
	mock *MockAuthService
}

// NewMockAuthService creates a new mock instance.
func NewMockAuthService(ctrl *gomock.Controller) *MockAuthService {
	mock := &MockAuthService{ctrl: ctrl}
	mock.recorder = &MockAuthServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthService) EXPECT() *MockAuthServiceMockRecorder {
	return m.recorder
}

// ConfirmPassword mocks base method.
func (m *MockAuthService) ConfirmPassword(ctx context.Context, token, password string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConfirmPassword", ctx, token, password)
	ret0, _ := ret[0].(error)
	return ret0
}

// ConfirmPassword indicates an expected call of ConfirmPassword.
func (mr *MockAuthServiceMockRecorder) ConfirmPassword(ctx, token, password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConfirmPassword", reflect.TypeOf((*MockAuthService)(nil).ConfirmPassword), ctx, token, password)
}

// Login mocks base method.
func (m *MockAuthService) Login(ctx context.Context, email, password string) (*entity.Auth, string, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login", ctx, email, password)
	ret0, _ := ret[0].(*entity.Auth)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(string)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// Login indicates an expected call of Login.
func (mr *MockAuthServiceMockRecorder) Login(ctx, email, password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockAuthService)(nil).Login), ctx, email, password)
}

// LoginOAuth mocks base method.
func (m *MockAuthService) LoginOAuth(ctx context.Context, code, codeVerifier string, provider entity.AuthProvider) (*entity.Auth, string, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoginOAuth", ctx, code, codeVerifier, provider)
	ret0, _ := ret[0].(*entity.Auth)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(string)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// LoginOAuth indicates an expected call of LoginOAuth.
func (mr *MockAuthServiceMockRecorder) LoginOAuth(ctx, code, codeVerifier, provider any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoginOAuth", reflect.TypeOf((*MockAuthService)(nil).LoginOAuth), ctx, code, codeVerifier, provider)
}

// Logout mocks base method.
func (m *MockAuthService) Logout(ctx context.Context, userID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Logout", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Logout indicates an expected call of Logout.
func (mr *MockAuthServiceMockRecorder) Logout(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Logout", reflect.TypeOf((*MockAuthService)(nil).Logout), ctx, userID)
}

// SendPasswordResetEmail mocks base method.
func (m *MockAuthService) SendPasswordResetEmail(ctx context.Context, email string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendPasswordResetEmail", ctx, email)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendPasswordResetEmail indicates an expected call of SendPasswordResetEmail.
func (mr *MockAuthServiceMockRecorder) SendPasswordResetEmail(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendPasswordResetEmail", reflect.TypeOf((*MockAuthService)(nil).SendPasswordResetEmail), ctx, email)
}

// SendVerificationEmail mocks base method.
func (m *MockAuthService) SendVerificationEmail(ctx context.Context, email string, userID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendVerificationEmail", ctx, email, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendVerificationEmail indicates an expected call of SendVerificationEmail.
func (mr *MockAuthServiceMockRecorder) SendVerificationEmail(ctx, email, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendVerificationEmail", reflect.TypeOf((*MockAuthService)(nil).SendVerificationEmail), ctx, email, userID)
}

// Signup mocks base method.
func (m *MockAuthService) Signup(ctx context.Context, email, password string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Signup", ctx, email, password)
	ret0, _ := ret[0].(error)
	return ret0
}

// Signup indicates an expected call of Signup.
func (mr *MockAuthServiceMockRecorder) Signup(ctx, email, password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Signup", reflect.TypeOf((*MockAuthService)(nil).Signup), ctx, email, password)
}

// VerifyEmail mocks base method.
func (m *MockAuthService) VerifyEmail(ctx context.Context, token string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyEmail", ctx, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// VerifyEmail indicates an expected call of VerifyEmail.
func (mr *MockAuthServiceMockRecorder) VerifyEmail(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyEmail", reflect.TypeOf((*MockAuthService)(nil).VerifyEmail), ctx, token)
}
