// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/repo/block.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/repo/block.go -destination=internal/mock/block.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	entity "github.com/icchon/matcha/api/internal/domain/entity"
	repo "github.com/icchon/matcha/api/internal/domain/repo"
	gomock "go.uber.org/mock/gomock"
)

// MockBlockQueryRepository is a mock of BlockQueryRepository interface.
type MockBlockQueryRepository struct {
	ctrl     *gomock.Controller
	recorder *MockBlockQueryRepositoryMockRecorder
	isgomock struct{}
}

// MockBlockQueryRepositoryMockRecorder is the mock recorder for MockBlockQueryRepository.
type MockBlockQueryRepositoryMockRecorder struct {
	mock *MockBlockQueryRepository
}

// NewMockBlockQueryRepository creates a new mock instance.
func NewMockBlockQueryRepository(ctrl *gomock.Controller) *MockBlockQueryRepository {
	mock := &MockBlockQueryRepository{ctrl: ctrl}
	mock.recorder = &MockBlockQueryRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBlockQueryRepository) EXPECT() *MockBlockQueryRepositoryMockRecorder {
	return m.recorder
}

// Find mocks base method.
func (m *MockBlockQueryRepository) Find(ctx context.Context, blockerID, blockedID uuid.UUID) (*entity.Block, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, blockerID, blockedID)
	ret0, _ := ret[0].(*entity.Block)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockBlockQueryRepositoryMockRecorder) Find(ctx, blockerID, blockedID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockBlockQueryRepository)(nil).Find), ctx, blockerID, blockedID)
}

// Query mocks base method.
func (m *MockBlockQueryRepository) Query(ctx context.Context, q *repo.BlockQuery) ([]*entity.Block, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Query", ctx, q)
	ret0, _ := ret[0].([]*entity.Block)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Query indicates an expected call of Query.
func (mr *MockBlockQueryRepositoryMockRecorder) Query(ctx, q any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Query", reflect.TypeOf((*MockBlockQueryRepository)(nil).Query), ctx, q)
}

// MockBlockCommandRepository is a mock of BlockCommandRepository interface.
type MockBlockCommandRepository struct {
	ctrl     *gomock.Controller
	recorder *MockBlockCommandRepositoryMockRecorder
	isgomock struct{}
}

// MockBlockCommandRepositoryMockRecorder is the mock recorder for MockBlockCommandRepository.
type MockBlockCommandRepositoryMockRecorder struct {
	mock *MockBlockCommandRepository
}

// NewMockBlockCommandRepository creates a new mock instance.
func NewMockBlockCommandRepository(ctrl *gomock.Controller) *MockBlockCommandRepository {
	mock := &MockBlockCommandRepository{ctrl: ctrl}
	mock.recorder = &MockBlockCommandRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBlockCommandRepository) EXPECT() *MockBlockCommandRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockBlockCommandRepository) Create(ctx context.Context, block *entity.Block) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, block)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockBlockCommandRepositoryMockRecorder) Create(ctx, block any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockBlockCommandRepository)(nil).Create), ctx, block)
}

// Delete mocks base method.
func (m *MockBlockCommandRepository) Delete(ctx context.Context, blockerID, blockedID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, blockerID, blockedID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockBlockCommandRepositoryMockRecorder) Delete(ctx, blockerID, blockedID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockBlockCommandRepository)(nil).Delete), ctx, blockerID, blockedID)
}

// MockBlockRepository is a mock of BlockRepository interface.
type MockBlockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockBlockRepositoryMockRecorder
	isgomock struct{}
}

// MockBlockRepositoryMockRecorder is the mock recorder for MockBlockRepository.
type MockBlockRepositoryMockRecorder struct {
	mock *MockBlockRepository
}

// NewMockBlockRepository creates a new mock instance.
func NewMockBlockRepository(ctrl *gomock.Controller) *MockBlockRepository {
	mock := &MockBlockRepository{ctrl: ctrl}
	mock.recorder = &MockBlockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBlockRepository) EXPECT() *MockBlockRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockBlockRepository) Create(ctx context.Context, block *entity.Block) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, block)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockBlockRepositoryMockRecorder) Create(ctx, block any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockBlockRepository)(nil).Create), ctx, block)
}

// Delete mocks base method.
func (m *MockBlockRepository) Delete(ctx context.Context, blockerID, blockedID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, blockerID, blockedID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockBlockRepositoryMockRecorder) Delete(ctx, blockerID, blockedID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockBlockRepository)(nil).Delete), ctx, blockerID, blockedID)
}

// Find mocks base method.
func (m *MockBlockRepository) Find(ctx context.Context, blockerID, blockedID uuid.UUID) (*entity.Block, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, blockerID, blockedID)
	ret0, _ := ret[0].(*entity.Block)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockBlockRepositoryMockRecorder) Find(ctx, blockerID, blockedID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockBlockRepository)(nil).Find), ctx, blockerID, blockedID)
}

// Query mocks base method.
func (m *MockBlockRepository) Query(ctx context.Context, q *repo.BlockQuery) ([]*entity.Block, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Query", ctx, q)
	ret0, _ := ret[0].([]*entity.Block)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Query indicates an expected call of Query.
func (mr *MockBlockRepositoryMockRecorder) Query(ctx, q any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Query", reflect.TypeOf((*MockBlockRepository)(nil).Query), ctx, q)
}
