// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/service/chat.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/service/chat.go -destination=internal/mock/chat_service.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	entity "github.com/icchon/matcha/api/internal/domain/entity"
	service "github.com/icchon/matcha/api/internal/domain/service"
	gomock "go.uber.org/mock/gomock"
)

// MockChatService is a mock of ChatService interface.
type MockChatService struct {
	ctrl     *gomock.Controller
	recorder *MockChatServiceMockRecorder
	isgomock struct{}
}

// MockChatServiceMockRecorder is the mock recorder for MockChatService.
type MockChatServiceMockRecorder struct {
	mock *MockChatService
}

// NewMockChatService creates a new mock instance.
func NewMockChatService(ctrl *gomock.Controller) *MockChatService {
	mock := &MockChatService{ctrl: ctrl}
	mock.recorder = &MockChatServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChatService) EXPECT() *MockChatServiceMockRecorder {
	return m.recorder
}

// GetChatMessages mocks base method.
func (m *MockChatService) GetChatMessages(ctx context.Context, params *service.GetChatMessagesParams) ([]*entity.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChatMessages", ctx, params)
	ret0, _ := ret[0].([]*entity.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetChatMessages indicates an expected call of GetChatMessages.
func (mr *MockChatServiceMockRecorder) GetChatMessages(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChatMessages", reflect.TypeOf((*MockChatService)(nil).GetChatMessages), ctx, params)
}

// GetChatsForUser mocks base method.
func (m *MockChatService) GetChatsForUser(ctx context.Context, userID uuid.UUID) ([]*service.Chat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChatsForUser", ctx, userID)
	ret0, _ := ret[0].([]*service.Chat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetChatsForUser indicates an expected call of GetChatsForUser.
func (mr *MockChatServiceMockRecorder) GetChatsForUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChatsForUser", reflect.TypeOf((*MockChatService)(nil).GetChatsForUser), ctx, userID)
}
