// Code generated by MockGen. DO NOT EDIT.
// Source: domain/repo/connection.go
//
// Generated by this command:
//
//	mockgen -source domain/repo/connection.go -destination mock/connection_repo.go -package mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	entity "github.com/icchon/matcha/api/internal/domain/entity"
	repo "github.com/icchon/matcha/api/internal/domain/repo"
	gomock "go.uber.org/mock/gomock"
)

// MockConnectionQueryRepository is a mock of ConnectionQueryRepository interface.
type MockConnectionQueryRepository struct {
	ctrl     *gomock.Controller
	recorder *MockConnectionQueryRepositoryMockRecorder
	isgomock struct{}
}

// MockConnectionQueryRepositoryMockRecorder is the mock recorder for MockConnectionQueryRepository.
type MockConnectionQueryRepositoryMockRecorder struct {
	mock *MockConnectionQueryRepository
}

// NewMockConnectionQueryRepository creates a new mock instance.
func NewMockConnectionQueryRepository(ctrl *gomock.Controller) *MockConnectionQueryRepository {
	mock := &MockConnectionQueryRepository{ctrl: ctrl}
	mock.recorder = &MockConnectionQueryRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConnectionQueryRepository) EXPECT() *MockConnectionQueryRepositoryMockRecorder {
	return m.recorder
}

// Find mocks base method.
func (m *MockConnectionQueryRepository) Find(ctx context.Context, user1ID, user2ID uuid.UUID) (*entity.Connection, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, user1ID, user2ID)
	ret0, _ := ret[0].(*entity.Connection)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockConnectionQueryRepositoryMockRecorder) Find(ctx, user1ID, user2ID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockConnectionQueryRepository)(nil).Find), ctx, user1ID, user2ID)
}

// Query mocks base method.
func (m *MockConnectionQueryRepository) Query(ctx context.Context, q *repo.ConnectionQuery) ([]*entity.Connection, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Query", ctx, q)
	ret0, _ := ret[0].([]*entity.Connection)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Query indicates an expected call of Query.
func (mr *MockConnectionQueryRepositoryMockRecorder) Query(ctx, q any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Query", reflect.TypeOf((*MockConnectionQueryRepository)(nil).Query), ctx, q)
}

// MockConnectionCommandRepository is a mock of ConnectionCommandRepository interface.
type MockConnectionCommandRepository struct {
	ctrl     *gomock.Controller
	recorder *MockConnectionCommandRepositoryMockRecorder
	isgomock struct{}
}

// MockConnectionCommandRepositoryMockRecorder is the mock recorder for MockConnectionCommandRepository.
type MockConnectionCommandRepositoryMockRecorder struct {
	mock *MockConnectionCommandRepository
}

// NewMockConnectionCommandRepository creates a new mock instance.
func NewMockConnectionCommandRepository(ctrl *gomock.Controller) *MockConnectionCommandRepository {
	mock := &MockConnectionCommandRepository{ctrl: ctrl}
	mock.recorder = &MockConnectionCommandRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConnectionCommandRepository) EXPECT() *MockConnectionCommandRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockConnectionCommandRepository) Create(ctx context.Context, connection *entity.Connection) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, connection)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockConnectionCommandRepositoryMockRecorder) Create(ctx, connection any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockConnectionCommandRepository)(nil).Create), ctx, connection)
}

// Delete mocks base method.
func (m *MockConnectionCommandRepository) Delete(ctx context.Context, user1ID, user2ID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, user1ID, user2ID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockConnectionCommandRepositoryMockRecorder) Delete(ctx, user1ID, user2ID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockConnectionCommandRepository)(nil).Delete), ctx, user1ID, user2ID)
}

// MockConnectionRepository is a mock of ConnectionRepository interface.
type MockConnectionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockConnectionRepositoryMockRecorder
	isgomock struct{}
}

// MockConnectionRepositoryMockRecorder is the mock recorder for MockConnectionRepository.
type MockConnectionRepositoryMockRecorder struct {
	mock *MockConnectionRepository
}

// NewMockConnectionRepository creates a new mock instance.
func NewMockConnectionRepository(ctrl *gomock.Controller) *MockConnectionRepository {
	mock := &MockConnectionRepository{ctrl: ctrl}
	mock.recorder = &MockConnectionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConnectionRepository) EXPECT() *MockConnectionRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockConnectionRepository) Create(ctx context.Context, connection *entity.Connection) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, connection)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockConnectionRepositoryMockRecorder) Create(ctx, connection any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockConnectionRepository)(nil).Create), ctx, connection)
}

// Delete mocks base method.
func (m *MockConnectionRepository) Delete(ctx context.Context, user1ID, user2ID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, user1ID, user2ID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockConnectionRepositoryMockRecorder) Delete(ctx, user1ID, user2ID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockConnectionRepository)(nil).Delete), ctx, user1ID, user2ID)
}

// Find mocks base method.
func (m *MockConnectionRepository) Find(ctx context.Context, user1ID, user2ID uuid.UUID) (*entity.Connection, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, user1ID, user2ID)
	ret0, _ := ret[0].(*entity.Connection)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockConnectionRepositoryMockRecorder) Find(ctx, user1ID, user2ID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockConnectionRepository)(nil).Find), ctx, user1ID, user2ID)
}

// Query mocks base method.
func (m *MockConnectionRepository) Query(ctx context.Context, q *repo.ConnectionQuery) ([]*entity.Connection, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Query", ctx, q)
	ret0, _ := ret[0].([]*entity.Connection)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Query indicates an expected call of Query.
func (mr *MockConnectionRepositoryMockRecorder) Query(ctx, q any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Query", reflect.TypeOf((*MockConnectionRepository)(nil).Query), ctx, q)
}
