// Code generated by MockGen. DO NOT EDIT.
// Source: domain/repo/like.go
//
// Generated by this command:
//
//	mockgen -source domain/repo/like.go -destination mock/like.go -package mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	entity "github.com/icchon/matcha/api/internal/domain/entity"
	repo "github.com/icchon/matcha/api/internal/domain/repo"
	gomock "go.uber.org/mock/gomock"
)

// MockLikeQueryRepository is a mock of LikeQueryRepository interface.
type MockLikeQueryRepository struct {
	ctrl     *gomock.Controller
	recorder *MockLikeQueryRepositoryMockRecorder
	isgomock struct{}
}

// MockLikeQueryRepositoryMockRecorder is the mock recorder for MockLikeQueryRepository.
type MockLikeQueryRepositoryMockRecorder struct {
	mock *MockLikeQueryRepository
}

// NewMockLikeQueryRepository creates a new mock instance.
func NewMockLikeQueryRepository(ctrl *gomock.Controller) *MockLikeQueryRepository {
	mock := &MockLikeQueryRepository{ctrl: ctrl}
	mock.recorder = &MockLikeQueryRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLikeQueryRepository) EXPECT() *MockLikeQueryRepositoryMockRecorder {
	return m.recorder
}

// Find mocks base method.
func (m *MockLikeQueryRepository) Find(ctx context.Context, likerID, likedID uuid.UUID) (*entity.Like, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, likerID, likedID)
	ret0, _ := ret[0].(*entity.Like)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockLikeQueryRepositoryMockRecorder) Find(ctx, likerID, likedID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockLikeQueryRepository)(nil).Find), ctx, likerID, likedID)
}

// Query mocks base method.
func (m *MockLikeQueryRepository) Query(ctx context.Context, q *repo.LikeQuery) ([]*entity.Like, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Query", ctx, q)
	ret0, _ := ret[0].([]*entity.Like)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Query indicates an expected call of Query.
func (mr *MockLikeQueryRepositoryMockRecorder) Query(ctx, q any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Query", reflect.TypeOf((*MockLikeQueryRepository)(nil).Query), ctx, q)
}

// MockLikeCommandRepository is a mock of LikeCommandRepository interface.
type MockLikeCommandRepository struct {
	ctrl     *gomock.Controller
	recorder *MockLikeCommandRepositoryMockRecorder
	isgomock struct{}
}

// MockLikeCommandRepositoryMockRecorder is the mock recorder for MockLikeCommandRepository.
type MockLikeCommandRepositoryMockRecorder struct {
	mock *MockLikeCommandRepository
}

// NewMockLikeCommandRepository creates a new mock instance.
func NewMockLikeCommandRepository(ctrl *gomock.Controller) *MockLikeCommandRepository {
	mock := &MockLikeCommandRepository{ctrl: ctrl}
	mock.recorder = &MockLikeCommandRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLikeCommandRepository) EXPECT() *MockLikeCommandRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockLikeCommandRepository) Create(ctx context.Context, like *entity.Like) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, like)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockLikeCommandRepositoryMockRecorder) Create(ctx, like any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockLikeCommandRepository)(nil).Create), ctx, like)
}

// Delete mocks base method.
func (m *MockLikeCommandRepository) Delete(ctx context.Context, likerID, likedID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, likerID, likedID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockLikeCommandRepositoryMockRecorder) Delete(ctx, likerID, likedID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockLikeCommandRepository)(nil).Delete), ctx, likerID, likedID)
}

// MockLikeRepository is a mock of LikeRepository interface.
type MockLikeRepository struct {
	ctrl     *gomock.Controller
	recorder *MockLikeRepositoryMockRecorder
	isgomock struct{}
}

// MockLikeRepositoryMockRecorder is the mock recorder for MockLikeRepository.
type MockLikeRepositoryMockRecorder struct {
	mock *MockLikeRepository
}

// NewMockLikeRepository creates a new mock instance.
func NewMockLikeRepository(ctrl *gomock.Controller) *MockLikeRepository {
	mock := &MockLikeRepository{ctrl: ctrl}
	mock.recorder = &MockLikeRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLikeRepository) EXPECT() *MockLikeRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockLikeRepository) Create(ctx context.Context, like *entity.Like) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, like)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockLikeRepositoryMockRecorder) Create(ctx, like any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockLikeRepository)(nil).Create), ctx, like)
}

// Delete mocks base method.
func (m *MockLikeRepository) Delete(ctx context.Context, likerID, likedID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, likerID, likedID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockLikeRepositoryMockRecorder) Delete(ctx, likerID, likedID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockLikeRepository)(nil).Delete), ctx, likerID, likedID)
}

// Find mocks base method.
func (m *MockLikeRepository) Find(ctx context.Context, likerID, likedID uuid.UUID) (*entity.Like, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, likerID, likedID)
	ret0, _ := ret[0].(*entity.Like)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockLikeRepositoryMockRecorder) Find(ctx, likerID, likedID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockLikeRepository)(nil).Find), ctx, likerID, likedID)
}

// Query mocks base method.
func (m *MockLikeRepository) Query(ctx context.Context, q *repo.LikeQuery) ([]*entity.Like, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Query", ctx, q)
	ret0, _ := ret[0].([]*entity.Like)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Query indicates an expected call of Query.
func (mr *MockLikeRepositoryMockRecorder) Query(ctx, q any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Query", reflect.TypeOf((*MockLikeRepository)(nil).Query), ctx, q)
}
