// Code generated by MockGen. DO NOT EDIT.
// Source: domain/repo/mail.go
//
// Generated by this command:
//
//	mockgen -source domain/repo/mail.go -destination mock/mail_client.go -package mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockMailClient is a mock of MailClient interface.
type MockMailClient struct {
	ctrl     *gomock.Controller
	recorder *MockMailClientMockRecorder
	isgomock struct{}
}

// MockMailClientMockRecorder is the mock recorder for MockMailClient.
type MockMailClientMockRecorder struct {
	mock *MockMailClient
}

// NewMockMailClient creates a new mock instance.
func NewMockMailClient(ctrl *gomock.Controller) *MockMailClient {
	mock := &MockMailClient{ctrl: ctrl}
	mock.recorder = &MockMailClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMailClient) EXPECT() *MockMailClientMockRecorder {
	return m.recorder
}

// SendRawEmail mocks base method.
func (m *MockMailClient) SendRawEmail(ctx context.Context, toEmail, subject, htmlBody, textBody string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendRawEmail", ctx, toEmail, subject, htmlBody, textBody)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendRawEmail indicates an expected call of SendRawEmail.
func (mr *MockMailClientMockRecorder) SendRawEmail(ctx, toEmail, subject, htmlBody, textBody any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendRawEmail", reflect.TypeOf((*MockMailClient)(nil).SendRawEmail), ctx, toEmail, subject, htmlBody, textBody)
}
