// Code generated by MockGen. DO NOT EDIT.
// Source: domain/repo/message.go
//
// Generated by this command:
//
//	mockgen -source domain/repo/message.go -destination mock/message.go -package mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	entity "github.com/icchon/matcha/api/internal/domain/entity"
	repo "github.com/icchon/matcha/api/internal/domain/repo"
	gomock "go.uber.org/mock/gomock"
)

// MockMessageQueryRepository is a mock of MessageQueryRepository interface.
type MockMessageQueryRepository struct {
	ctrl     *gomock.Controller
	recorder *MockMessageQueryRepositoryMockRecorder
	isgomock struct{}
}

// MockMessageQueryRepositoryMockRecorder is the mock recorder for MockMessageQueryRepository.
type MockMessageQueryRepositoryMockRecorder struct {
	mock *MockMessageQueryRepository
}

// NewMockMessageQueryRepository creates a new mock instance.
func NewMockMessageQueryRepository(ctrl *gomock.Controller) *MockMessageQueryRepository {
	mock := &MockMessageQueryRepository{ctrl: ctrl}
	mock.recorder = &MockMessageQueryRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMessageQueryRepository) EXPECT() *MockMessageQueryRepositoryMockRecorder {
	return m.recorder
}

// Find mocks base method.
func (m *MockMessageQueryRepository) Find(ctx context.Context, messageID int64) (*entity.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, messageID)
	ret0, _ := ret[0].(*entity.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockMessageQueryRepositoryMockRecorder) Find(ctx, messageID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockMessageQueryRepository)(nil).Find), ctx, messageID)
}

// Query mocks base method.
func (m *MockMessageQueryRepository) Query(ctx context.Context, q *repo.MessageQuery) ([]*entity.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Query", ctx, q)
	ret0, _ := ret[0].([]*entity.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Query indicates an expected call of Query.
func (mr *MockMessageQueryRepositoryMockRecorder) Query(ctx, q any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Query", reflect.TypeOf((*MockMessageQueryRepository)(nil).Query), ctx, q)
}

// MockMessageCommandRepository is a mock of MessageCommandRepository interface.
type MockMessageCommandRepository struct {
	ctrl     *gomock.Controller
	recorder *MockMessageCommandRepositoryMockRecorder
	isgomock struct{}
}

// MockMessageCommandRepositoryMockRecorder is the mock recorder for MockMessageCommandRepository.
type MockMessageCommandRepositoryMockRecorder struct {
	mock *MockMessageCommandRepository
}

// NewMockMessageCommandRepository creates a new mock instance.
func NewMockMessageCommandRepository(ctrl *gomock.Controller) *MockMessageCommandRepository {
	mock := &MockMessageCommandRepository{ctrl: ctrl}
	mock.recorder = &MockMessageCommandRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMessageCommandRepository) EXPECT() *MockMessageCommandRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockMessageCommandRepository) Create(ctx context.Context, message *entity.Message) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, message)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockMessageCommandRepositoryMockRecorder) Create(ctx, message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockMessageCommandRepository)(nil).Create), ctx, message)
}

// Delete mocks base method.
func (m *MockMessageCommandRepository) Delete(ctx context.Context, messageID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, messageID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockMessageCommandRepositoryMockRecorder) Delete(ctx, messageID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockMessageCommandRepository)(nil).Delete), ctx, messageID)
}

// Update mocks base method.
func (m *MockMessageCommandRepository) Update(ctx context.Context, message *entity.Message) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, message)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockMessageCommandRepositoryMockRecorder) Update(ctx, message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockMessageCommandRepository)(nil).Update), ctx, message)
}

// MockMessageRepository is a mock of MessageRepository interface.
type MockMessageRepository struct {
	ctrl     *gomock.Controller
	recorder *MockMessageRepositoryMockRecorder
	isgomock struct{}
}

// MockMessageRepositoryMockRecorder is the mock recorder for MockMessageRepository.
type MockMessageRepositoryMockRecorder struct {
	mock *MockMessageRepository
}

// NewMockMessageRepository creates a new mock instance.
func NewMockMessageRepository(ctrl *gomock.Controller) *MockMessageRepository {
	mock := &MockMessageRepository{ctrl: ctrl}
	mock.recorder = &MockMessageRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMessageRepository) EXPECT() *MockMessageRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockMessageRepository) Create(ctx context.Context, message *entity.Message) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, message)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockMessageRepositoryMockRecorder) Create(ctx, message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockMessageRepository)(nil).Create), ctx, message)
}

// Delete mocks base method.
func (m *MockMessageRepository) Delete(ctx context.Context, messageID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, messageID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockMessageRepositoryMockRecorder) Delete(ctx, messageID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockMessageRepository)(nil).Delete), ctx, messageID)
}

// Find mocks base method.
func (m *MockMessageRepository) Find(ctx context.Context, messageID int64) (*entity.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, messageID)
	ret0, _ := ret[0].(*entity.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockMessageRepositoryMockRecorder) Find(ctx, messageID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockMessageRepository)(nil).Find), ctx, messageID)
}

// Query mocks base method.
func (m *MockMessageRepository) Query(ctx context.Context, q *repo.MessageQuery) ([]*entity.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Query", ctx, q)
	ret0, _ := ret[0].([]*entity.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Query indicates an expected call of Query.
func (mr *MockMessageRepositoryMockRecorder) Query(ctx, q any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Query", reflect.TypeOf((*MockMessageRepository)(nil).Query), ctx, q)
}

// Update mocks base method.
func (m *MockMessageRepository) Update(ctx context.Context, message *entity.Message) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, message)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockMessageRepositoryMockRecorder) Update(ctx, message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockMessageRepository)(nil).Update), ctx, message)
}
