// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/repo/notification.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/repo/notification.go -destination=internal/mock/notification.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	entity "github.com/icchon/matcha/api/internal/domain/entity"
	repo "github.com/icchon/matcha/api/internal/domain/repo"
	gomock "go.uber.org/mock/gomock"
)

// MockNotificationQueryRepository is a mock of NotificationQueryRepository interface.
type MockNotificationQueryRepository struct {
	ctrl     *gomock.Controller
	recorder *MockNotificationQueryRepositoryMockRecorder
	isgomock struct{}
}

// MockNotificationQueryRepositoryMockRecorder is the mock recorder for MockNotificationQueryRepository.
type MockNotificationQueryRepositoryMockRecorder struct {
	mock *MockNotificationQueryRepository
}

// NewMockNotificationQueryRepository creates a new mock instance.
func NewMockNotificationQueryRepository(ctrl *gomock.Controller) *MockNotificationQueryRepository {
	mock := &MockNotificationQueryRepository{ctrl: ctrl}
	mock.recorder = &MockNotificationQueryRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNotificationQueryRepository) EXPECT() *MockNotificationQueryRepositoryMockRecorder {
	return m.recorder
}

// Find mocks base method.
func (m *MockNotificationQueryRepository) Find(ctx context.Context, notificationID int64) (*entity.Notification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, notificationID)
	ret0, _ := ret[0].(*entity.Notification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockNotificationQueryRepositoryMockRecorder) Find(ctx, notificationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockNotificationQueryRepository)(nil).Find), ctx, notificationID)
}

// Query mocks base method.
func (m *MockNotificationQueryRepository) Query(ctx context.Context, q *repo.NotificationQuery) ([]*entity.Notification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Query", ctx, q)
	ret0, _ := ret[0].([]*entity.Notification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Query indicates an expected call of Query.
func (mr *MockNotificationQueryRepositoryMockRecorder) Query(ctx, q any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Query", reflect.TypeOf((*MockNotificationQueryRepository)(nil).Query), ctx, q)
}

// MockNotificationCommandRepository is a mock of NotificationCommandRepository interface.
type MockNotificationCommandRepository struct {
	ctrl     *gomock.Controller
	recorder *MockNotificationCommandRepositoryMockRecorder
	isgomock struct{}
}

// MockNotificationCommandRepositoryMockRecorder is the mock recorder for MockNotificationCommandRepository.
type MockNotificationCommandRepositoryMockRecorder struct {
	mock *MockNotificationCommandRepository
}

// NewMockNotificationCommandRepository creates a new mock instance.
func NewMockNotificationCommandRepository(ctrl *gomock.Controller) *MockNotificationCommandRepository {
	mock := &MockNotificationCommandRepository{ctrl: ctrl}
	mock.recorder = &MockNotificationCommandRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNotificationCommandRepository) EXPECT() *MockNotificationCommandRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockNotificationCommandRepository) Create(ctx context.Context, notification *entity.Notification) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, notification)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockNotificationCommandRepositoryMockRecorder) Create(ctx, notification any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockNotificationCommandRepository)(nil).Create), ctx, notification)
}

// Delete mocks base method.
func (m *MockNotificationCommandRepository) Delete(ctx context.Context, notificationID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, notificationID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockNotificationCommandRepositoryMockRecorder) Delete(ctx, notificationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockNotificationCommandRepository)(nil).Delete), ctx, notificationID)
}

// Update mocks base method.
func (m *MockNotificationCommandRepository) Update(ctx context.Context, notification *entity.Notification) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, notification)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockNotificationCommandRepositoryMockRecorder) Update(ctx, notification any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockNotificationCommandRepository)(nil).Update), ctx, notification)
}

// MockNotificationRepository is a mock of NotificationRepository interface.
type MockNotificationRepository struct {
	ctrl     *gomock.Controller
	recorder *MockNotificationRepositoryMockRecorder
	isgomock struct{}
}

// MockNotificationRepositoryMockRecorder is the mock recorder for MockNotificationRepository.
type MockNotificationRepositoryMockRecorder struct {
	mock *MockNotificationRepository
}

// NewMockNotificationRepository creates a new mock instance.
func NewMockNotificationRepository(ctrl *gomock.Controller) *MockNotificationRepository {
	mock := &MockNotificationRepository{ctrl: ctrl}
	mock.recorder = &MockNotificationRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNotificationRepository) EXPECT() *MockNotificationRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockNotificationRepository) Create(ctx context.Context, notification *entity.Notification) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, notification)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockNotificationRepositoryMockRecorder) Create(ctx, notification any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockNotificationRepository)(nil).Create), ctx, notification)
}

// Delete mocks base method.
func (m *MockNotificationRepository) Delete(ctx context.Context, notificationID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, notificationID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockNotificationRepositoryMockRecorder) Delete(ctx, notificationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockNotificationRepository)(nil).Delete), ctx, notificationID)
}

// Find mocks base method.
func (m *MockNotificationRepository) Find(ctx context.Context, notificationID int64) (*entity.Notification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, notificationID)
	ret0, _ := ret[0].(*entity.Notification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockNotificationRepositoryMockRecorder) Find(ctx, notificationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockNotificationRepository)(nil).Find), ctx, notificationID)
}

// Query mocks base method.
func (m *MockNotificationRepository) Query(ctx context.Context, q *repo.NotificationQuery) ([]*entity.Notification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Query", ctx, q)
	ret0, _ := ret[0].([]*entity.Notification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Query indicates an expected call of Query.
func (mr *MockNotificationRepositoryMockRecorder) Query(ctx, q any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Query", reflect.TypeOf((*MockNotificationRepository)(nil).Query), ctx, q)
}

// Update mocks base method.
func (m *MockNotificationRepository) Update(ctx context.Context, notification *entity.Notification) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, notification)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockNotificationRepositoryMockRecorder) Update(ctx, notification any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockNotificationRepository)(nil).Update), ctx, notification)
}
