// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/service/notice.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/service/notice.go -destination=internal/mock/notification_service.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	entity "github.com/icchon/matcha/api/internal/domain/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockNotificationService is a mock of NotificationService interface.
type MockNotificationService struct {
	ctrl     *gomock.Controller
	recorder *MockNotificationServiceMockRecorder
	isgomock struct{}
}

// MockNotificationServiceMockRecorder is the mock recorder for MockNotificationService.
type MockNotificationServiceMockRecorder struct {
	mock *MockNotificationService
}

// NewMockNotificationService creates a new mock instance.
func NewMockNotificationService(ctrl *gomock.Controller) *MockNotificationService {
	mock := &MockNotificationService{ctrl: ctrl}
	mock.recorder = &MockNotificationServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNotificationService) EXPECT() *MockNotificationServiceMockRecorder {
	return m.recorder
}

// CreateAndSendNotification mocks base method.
func (m *MockNotificationService) CreateAndSendNotification(ctx context.Context, senderID, recipiendID uuid.UUID, notifType entity.NotificationType) (*entity.Notification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAndSendNotification", ctx, senderID, recipiendID, notifType)
	ret0, _ := ret[0].(*entity.Notification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAndSendNotification indicates an expected call of CreateAndSendNotification.
func (mr *MockNotificationServiceMockRecorder) CreateAndSendNotification(ctx, senderID, recipiendID, notifType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAndSendNotification", reflect.TypeOf((*MockNotificationService)(nil).CreateAndSendNotification), ctx, senderID, recipiendID, notifType)
}

// GetNotifications mocks base method.
func (m *MockNotificationService) GetNotifications(ctx context.Context, recipientID uuid.UUID) ([]*entity.Notification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNotifications", ctx, recipientID)
	ret0, _ := ret[0].([]*entity.Notification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNotifications indicates an expected call of GetNotifications.
func (mr *MockNotificationServiceMockRecorder) GetNotifications(ctx, recipientID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNotifications", reflect.TypeOf((*MockNotificationService)(nil).GetNotifications), ctx, recipientID)
}
