// Code generated by MockGen. DO NOT EDIT.
// Source: domain/repo/password_reset.go
//
// Generated by this command:
//
//	mockgen -source domain/repo/password_reset.go -destination mock/password_reset.go -package mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	entity "github.com/icchon/matcha/api/internal/domain/entity"
	repo "github.com/icchon/matcha/api/internal/domain/repo"
	gomock "go.uber.org/mock/gomock"
)

// MockPasswordResetQueryRepository is a mock of PasswordResetQueryRepository interface.
type MockPasswordResetQueryRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPasswordResetQueryRepositoryMockRecorder
	isgomock struct{}
}

// MockPasswordResetQueryRepositoryMockRecorder is the mock recorder for MockPasswordResetQueryRepository.
type MockPasswordResetQueryRepositoryMockRecorder struct {
	mock *MockPasswordResetQueryRepository
}

// NewMockPasswordResetQueryRepository creates a new mock instance.
func NewMockPasswordResetQueryRepository(ctrl *gomock.Controller) *MockPasswordResetQueryRepository {
	mock := &MockPasswordResetQueryRepository{ctrl: ctrl}
	mock.recorder = &MockPasswordResetQueryRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPasswordResetQueryRepository) EXPECT() *MockPasswordResetQueryRepositoryMockRecorder {
	return m.recorder
}

// Find mocks base method.
func (m *MockPasswordResetQueryRepository) Find(ctx context.Context, token string) (*entity.PasswordReset, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, token)
	ret0, _ := ret[0].(*entity.PasswordReset)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockPasswordResetQueryRepositoryMockRecorder) Find(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockPasswordResetQueryRepository)(nil).Find), ctx, token)
}

// Query mocks base method.
func (m *MockPasswordResetQueryRepository) Query(ctx context.Context, q *repo.PasswordResetQuery) ([]*entity.PasswordReset, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Query", ctx, q)
	ret0, _ := ret[0].([]*entity.PasswordReset)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Query indicates an expected call of Query.
func (mr *MockPasswordResetQueryRepositoryMockRecorder) Query(ctx, q any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Query", reflect.TypeOf((*MockPasswordResetQueryRepository)(nil).Query), ctx, q)
}

// MockPasswordResetCommandRepository is a mock of PasswordResetCommandRepository interface.
type MockPasswordResetCommandRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPasswordResetCommandRepositoryMockRecorder
	isgomock struct{}
}

// MockPasswordResetCommandRepositoryMockRecorder is the mock recorder for MockPasswordResetCommandRepository.
type MockPasswordResetCommandRepositoryMockRecorder struct {
	mock *MockPasswordResetCommandRepository
}

// NewMockPasswordResetCommandRepository creates a new mock instance.
func NewMockPasswordResetCommandRepository(ctrl *gomock.Controller) *MockPasswordResetCommandRepository {
	mock := &MockPasswordResetCommandRepository{ctrl: ctrl}
	mock.recorder = &MockPasswordResetCommandRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPasswordResetCommandRepository) EXPECT() *MockPasswordResetCommandRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockPasswordResetCommandRepository) Create(ctx context.Context, params repo.CreatePasswordResetParams) (*entity.PasswordReset, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, params)
	ret0, _ := ret[0].(*entity.PasswordReset)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockPasswordResetCommandRepositoryMockRecorder) Create(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPasswordResetCommandRepository)(nil).Create), ctx, params)
}

// Delete mocks base method.
func (m *MockPasswordResetCommandRepository) Delete(ctx context.Context, token string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockPasswordResetCommandRepositoryMockRecorder) Delete(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockPasswordResetCommandRepository)(nil).Delete), ctx, token)
}

// Update mocks base method.
func (m *MockPasswordResetCommandRepository) Update(ctx context.Context, passwordReset *entity.PasswordReset) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, passwordReset)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockPasswordResetCommandRepositoryMockRecorder) Update(ctx, passwordReset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockPasswordResetCommandRepository)(nil).Update), ctx, passwordReset)
}

// MockPasswordResetRepository is a mock of PasswordResetRepository interface.
type MockPasswordResetRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPasswordResetRepositoryMockRecorder
	isgomock struct{}
}

// MockPasswordResetRepositoryMockRecorder is the mock recorder for MockPasswordResetRepository.
type MockPasswordResetRepositoryMockRecorder struct {
	mock *MockPasswordResetRepository
}

// NewMockPasswordResetRepository creates a new mock instance.
func NewMockPasswordResetRepository(ctrl *gomock.Controller) *MockPasswordResetRepository {
	mock := &MockPasswordResetRepository{ctrl: ctrl}
	mock.recorder = &MockPasswordResetRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPasswordResetRepository) EXPECT() *MockPasswordResetRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockPasswordResetRepository) Create(ctx context.Context, params repo.CreatePasswordResetParams) (*entity.PasswordReset, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, params)
	ret0, _ := ret[0].(*entity.PasswordReset)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockPasswordResetRepositoryMockRecorder) Create(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPasswordResetRepository)(nil).Create), ctx, params)
}

// Delete mocks base method.
func (m *MockPasswordResetRepository) Delete(ctx context.Context, token string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockPasswordResetRepositoryMockRecorder) Delete(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockPasswordResetRepository)(nil).Delete), ctx, token)
}

// Find mocks base method.
func (m *MockPasswordResetRepository) Find(ctx context.Context, token string) (*entity.PasswordReset, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, token)
	ret0, _ := ret[0].(*entity.PasswordReset)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockPasswordResetRepositoryMockRecorder) Find(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockPasswordResetRepository)(nil).Find), ctx, token)
}

// Query mocks base method.
func (m *MockPasswordResetRepository) Query(ctx context.Context, q *repo.PasswordResetQuery) ([]*entity.PasswordReset, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Query", ctx, q)
	ret0, _ := ret[0].([]*entity.PasswordReset)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Query indicates an expected call of Query.
func (mr *MockPasswordResetRepositoryMockRecorder) Query(ctx, q any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Query", reflect.TypeOf((*MockPasswordResetRepository)(nil).Query), ctx, q)
}

// Update mocks base method.
func (m *MockPasswordResetRepository) Update(ctx context.Context, passwordReset *entity.PasswordReset) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, passwordReset)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockPasswordResetRepositoryMockRecorder) Update(ctx, passwordReset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockPasswordResetRepository)(nil).Update), ctx, passwordReset)
}
