// Code generated by MockGen. DO NOT EDIT.
// Source: domain/repo/picture.go
//
// Generated by this command:
//
//	mockgen -source domain/repo/picture.go -destination mock/picture_repo.go -package mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	entity "github.com/icchon/matcha/api/internal/domain/entity"
	repo "github.com/icchon/matcha/api/internal/domain/repo"
	gomock "go.uber.org/mock/gomock"
)

// MockPictureQueryRepository is a mock of PictureQueryRepository interface.
type MockPictureQueryRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPictureQueryRepositoryMockRecorder
	isgomock struct{}
}

// MockPictureQueryRepositoryMockRecorder is the mock recorder for MockPictureQueryRepository.
type MockPictureQueryRepositoryMockRecorder struct {
	mock *MockPictureQueryRepository
}

// NewMockPictureQueryRepository creates a new mock instance.
func NewMockPictureQueryRepository(ctrl *gomock.Controller) *MockPictureQueryRepository {
	mock := &MockPictureQueryRepository{ctrl: ctrl}
	mock.recorder = &MockPictureQueryRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPictureQueryRepository) EXPECT() *MockPictureQueryRepositoryMockRecorder {
	return m.recorder
}

// Find mocks base method.
func (m *MockPictureQueryRepository) Find(ctx context.Context, pictureID int32) (*entity.Picture, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, pictureID)
	ret0, _ := ret[0].(*entity.Picture)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockPictureQueryRepositoryMockRecorder) Find(ctx, pictureID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockPictureQueryRepository)(nil).Find), ctx, pictureID)
}

// Query mocks base method.
func (m *MockPictureQueryRepository) Query(ctx context.Context, q *repo.PictureQuery) ([]*entity.Picture, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Query", ctx, q)
	ret0, _ := ret[0].([]*entity.Picture)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Query indicates an expected call of Query.
func (mr *MockPictureQueryRepositoryMockRecorder) Query(ctx, q any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Query", reflect.TypeOf((*MockPictureQueryRepository)(nil).Query), ctx, q)
}

// MockPictureCommandRepository is a mock of PictureCommandRepository interface.
type MockPictureCommandRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPictureCommandRepositoryMockRecorder
	isgomock struct{}
}

// MockPictureCommandRepositoryMockRecorder is the mock recorder for MockPictureCommandRepository.
type MockPictureCommandRepositoryMockRecorder struct {
	mock *MockPictureCommandRepository
}

// NewMockPictureCommandRepository creates a new mock instance.
func NewMockPictureCommandRepository(ctrl *gomock.Controller) *MockPictureCommandRepository {
	mock := &MockPictureCommandRepository{ctrl: ctrl}
	mock.recorder = &MockPictureCommandRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPictureCommandRepository) EXPECT() *MockPictureCommandRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockPictureCommandRepository) Create(ctx context.Context, params repo.CreatePictureParams) (*entity.Picture, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, params)
	ret0, _ := ret[0].(*entity.Picture)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockPictureCommandRepositoryMockRecorder) Create(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPictureCommandRepository)(nil).Create), ctx, params)
}

// Delete mocks base method.
func (m *MockPictureCommandRepository) Delete(ctx context.Context, pictureID int32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, pictureID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockPictureCommandRepositoryMockRecorder) Delete(ctx, pictureID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockPictureCommandRepository)(nil).Delete), ctx, pictureID)
}

// Update mocks base method.
func (m *MockPictureCommandRepository) Update(ctx context.Context, picture *entity.Picture) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, picture)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockPictureCommandRepositoryMockRecorder) Update(ctx, picture any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockPictureCommandRepository)(nil).Update), ctx, picture)
}

// MockPictureRepository is a mock of PictureRepository interface.
type MockPictureRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPictureRepositoryMockRecorder
	isgomock struct{}
}

// MockPictureRepositoryMockRecorder is the mock recorder for MockPictureRepository.
type MockPictureRepositoryMockRecorder struct {
	mock *MockPictureRepository
}

// NewMockPictureRepository creates a new mock instance.
func NewMockPictureRepository(ctrl *gomock.Controller) *MockPictureRepository {
	mock := &MockPictureRepository{ctrl: ctrl}
	mock.recorder = &MockPictureRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPictureRepository) EXPECT() *MockPictureRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockPictureRepository) Create(ctx context.Context, params repo.CreatePictureParams) (*entity.Picture, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, params)
	ret0, _ := ret[0].(*entity.Picture)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockPictureRepositoryMockRecorder) Create(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPictureRepository)(nil).Create), ctx, params)
}

// Delete mocks base method.
func (m *MockPictureRepository) Delete(ctx context.Context, pictureID int32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, pictureID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockPictureRepositoryMockRecorder) Delete(ctx, pictureID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockPictureRepository)(nil).Delete), ctx, pictureID)
}

// Find mocks base method.
func (m *MockPictureRepository) Find(ctx context.Context, pictureID int32) (*entity.Picture, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, pictureID)
	ret0, _ := ret[0].(*entity.Picture)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockPictureRepositoryMockRecorder) Find(ctx, pictureID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockPictureRepository)(nil).Find), ctx, pictureID)
}

// Query mocks base method.
func (m *MockPictureRepository) Query(ctx context.Context, q *repo.PictureQuery) ([]*entity.Picture, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Query", ctx, q)
	ret0, _ := ret[0].([]*entity.Picture)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Query indicates an expected call of Query.
func (mr *MockPictureRepositoryMockRecorder) Query(ctx, q any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Query", reflect.TypeOf((*MockPictureRepository)(nil).Query), ctx, q)
}

// Update mocks base method.
func (m *MockPictureRepository) Update(ctx context.Context, picture *entity.Picture) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, picture)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockPictureRepositoryMockRecorder) Update(ctx, picture any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockPictureRepository)(nil).Update), ctx, picture)
}
