// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/icchon/matcha/api/internal/domain/service (interfaces: ProfileService)
//
// Generated by this command:
//
//	mockgen -destination=../../mock/profile_service.go -package=mock github.com/icchon/matcha/api/internal/domain/service ProfileService
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	entity "github.com/icchon/matcha/api/internal/domain/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockProfileService is a mock of ProfileService interface.
type MockProfileService struct {
	ctrl     *gomock.Controller
	recorder *MockProfileServiceMockRecorder
	isgomock struct{}
}

// MockProfileServiceMockRecorder is the mock recorder for MockProfileService.
type MockProfileServiceMockRecorder struct {
	mock *MockProfileService
}

// NewMockProfileService creates a new mock instance.
func NewMockProfileService(ctrl *gomock.Controller) *MockProfileService {
	mock := &MockProfileService{ctrl: ctrl}
	mock.recorder = &MockProfileServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProfileService) EXPECT() *MockProfileServiceMockRecorder {
	return m.recorder
}

// CreateProfile mocks base method.
func (m *MockProfileService) CreateProfile(ctx context.Context, profile *entity.UserProfile) (*entity.UserProfile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateProfile", ctx, profile)
	ret0, _ := ret[0].(*entity.UserProfile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateProfile indicates an expected call of CreateProfile.
func (mr *MockProfileServiceMockRecorder) CreateProfile(ctx, profile any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateProfile", reflect.TypeOf((*MockProfileService)(nil).CreateProfile), ctx, profile)
}

// DeletePicture mocks base method.
func (m *MockProfileService) DeletePicture(ctx context.Context, pictureID int32, userID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePicture", ctx, pictureID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePicture indicates an expected call of DeletePicture.
func (mr *MockProfileServiceMockRecorder) DeletePicture(ctx, pictureID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePicture", reflect.TypeOf((*MockProfileService)(nil).DeletePicture), ctx, pictureID, userID)
}

// FindMyViewedList mocks base method.
func (m *MockProfileService) FindMyViewedList(ctx context.Context, userID uuid.UUID) ([]*entity.View, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindMyViewedList", ctx, userID)
	ret0, _ := ret[0].([]*entity.View)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindMyViewedList indicates an expected call of FindMyViewedList.
func (mr *MockProfileServiceMockRecorder) FindMyViewedList(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindMyViewedList", reflect.TypeOf((*MockProfileService)(nil).FindMyViewedList), ctx, userID)
}

// FindPicture mocks base method.
func (m *MockProfileService) FindPicture(ctx context.Context, pictureID int32) (*entity.Picture, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindPicture", ctx, pictureID)
	ret0, _ := ret[0].(*entity.Picture)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindPicture indicates an expected call of FindPicture.
func (mr *MockProfileServiceMockRecorder) FindPicture(ctx, pictureID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindPicture", reflect.TypeOf((*MockProfileService)(nil).FindPicture), ctx, pictureID)
}

// FindPictures mocks base method.
func (m *MockProfileService) FindPictures(ctx context.Context, userID uuid.UUID) ([]*entity.Picture, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindPictures", ctx, userID)
	ret0, _ := ret[0].([]*entity.Picture)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindPictures indicates an expected call of FindPictures.
func (mr *MockProfileServiceMockRecorder) FindPictures(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindPictures", reflect.TypeOf((*MockProfileService)(nil).FindPictures), ctx, userID)
}

// FindWhoLikedMeList mocks base method.
func (m *MockProfileService) FindWhoLikedMeList(ctx context.Context, userID uuid.UUID) ([]*entity.Like, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindWhoLikedMeList", ctx, userID)
	ret0, _ := ret[0].([]*entity.Like)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindWhoLikedMeList indicates an expected call of FindWhoLikedMeList.
func (mr *MockProfileServiceMockRecorder) FindWhoLikedMeList(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindWhoLikedMeList", reflect.TypeOf((*MockProfileService)(nil).FindWhoLikedMeList), ctx, userID)
}

// FindWhoViewedMeList mocks base method.
func (m *MockProfileService) FindWhoViewedMeList(ctx context.Context, userID uuid.UUID) ([]*entity.View, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindWhoViewedMeList", ctx, userID)
	ret0, _ := ret[0].([]*entity.View)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindWhoViewedMeList indicates an expected call of FindWhoViewedMeList.
func (mr *MockProfileServiceMockRecorder) FindWhoViewedMeList(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindWhoViewedMeList", reflect.TypeOf((*MockProfileService)(nil).FindWhoViewedMeList), ctx, userID)
}

// UpdatePictureStatus mocks base method.
func (m *MockProfileService) UpdatePictureStatus(ctx context.Context, userID uuid.UUID, pictureID int32, isProfilePic bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePictureStatus", ctx, userID, pictureID, isProfilePic)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePictureStatus indicates an expected call of UpdatePictureStatus.
func (mr *MockProfileServiceMockRecorder) UpdatePictureStatus(ctx, userID, pictureID, isProfilePic any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePictureStatus", reflect.TypeOf((*MockProfileService)(nil).UpdatePictureStatus), ctx, userID, pictureID, isProfilePic)
}

// UpdateProfile mocks base method.
func (m *MockProfileService) UpdateProfile(ctx context.Context, userID uuid.UUID, profile *entity.UserProfile) (*entity.UserProfile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateProfile", ctx, userID, profile)
	ret0, _ := ret[0].(*entity.UserProfile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateProfile indicates an expected call of UpdateProfile.
func (mr *MockProfileServiceMockRecorder) UpdateProfile(ctx, userID, profile any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProfile", reflect.TypeOf((*MockProfileService)(nil).UpdateProfile), ctx, userID, profile)
}

// UploadPicture mocks base method.
func (m *MockProfileService) UploadPicture(ctx context.Context, userID uuid.UUID, image []byte) (*entity.Picture, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadPicture", ctx, userID, image)
	ret0, _ := ret[0].(*entity.Picture)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UploadPicture indicates an expected call of UploadPicture.
func (mr *MockProfileServiceMockRecorder) UploadPicture(ctx, userID, image any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadPicture", reflect.TypeOf((*MockProfileService)(nil).UploadPicture), ctx, userID, image)
}

// UploadPicutures mocks base method.
func (m *MockProfileService) UploadPicutures(ctx context.Context, userID uuid.UUID, images [][]byte) ([]*entity.Picture, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadPicutures", ctx, userID, images)
	ret0, _ := ret[0].([]*entity.Picture)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UploadPicutures indicates an expected call of UploadPicutures.
func (mr *MockProfileServiceMockRecorder) UploadPicutures(ctx, userID, images any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadPicutures", reflect.TypeOf((*MockProfileService)(nil).UploadPicutures), ctx, userID, images)
}

// VeiwProfile mocks base method.
func (m *MockProfileService) VeiwProfile(ctx context.Context, viewerID, viewedID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VeiwProfile", ctx, viewerID, viewedID)
	ret0, _ := ret[0].(error)
	return ret0
}

// VeiwProfile indicates an expected call of VeiwProfile.
func (mr *MockProfileServiceMockRecorder) VeiwProfile(ctx, viewerID, viewedID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VeiwProfile", reflect.TypeOf((*MockProfileService)(nil).VeiwProfile), ctx, viewerID, viewedID)
}
