// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/service/profile.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/service/profile.go -destination=internal/mock/profile_service.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	entity "github.com/icchon/matcha/api/internal/domain/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockProfileService is a mock of ProfileService interface.
type MockProfileService struct {
	ctrl     *gomock.Controller
	recorder *MockProfileServiceMockRecorder
	isgomock struct{}
}

// MockProfileServiceMockRecorder is the mock recorder for MockProfileService.
type MockProfileServiceMockRecorder struct {
	mock *MockProfileService
}

// NewMockProfileService creates a new mock instance.
func NewMockProfileService(ctrl *gomock.Controller) *MockProfileService {
	mock := &MockProfileService{ctrl: ctrl}
	mock.recorder = &MockProfileServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProfileService) EXPECT() *MockProfileServiceMockRecorder {
	return m.recorder
}

// CreateProfile mocks base method.
func (m *MockProfileService) CreateProfile(ctx context.Context, profile *entity.UserProfile) (*entity.UserProfile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateProfile", ctx, profile)
	ret0, _ := ret[0].(*entity.UserProfile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateProfile indicates an expected call of CreateProfile.
func (mr *MockProfileServiceMockRecorder) CreateProfile(ctx, profile any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateProfile", reflect.TypeOf((*MockProfileService)(nil).CreateProfile), ctx, profile)
}

// DeletePicture mocks base method.
func (m *MockProfileService) DeletePicture(ctx context.Context, pictureID int32, userID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePicture", ctx, pictureID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePicture indicates an expected call of DeletePicture.
func (mr *MockProfileServiceMockRecorder) DeletePicture(ctx, pictureID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePicture", reflect.TypeOf((*MockProfileService)(nil).DeletePicture), ctx, pictureID, userID)
}

// FindPicture mocks base method.
func (m *MockProfileService) FindPicture(ctx context.Context, pictureID int32) (*entity.Picture, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindPicture", ctx, pictureID)
	ret0, _ := ret[0].(*entity.Picture)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindPicture indicates an expected call of FindPicture.
func (mr *MockProfileServiceMockRecorder) FindPicture(ctx, pictureID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindPicture", reflect.TypeOf((*MockProfileService)(nil).FindPicture), ctx, pictureID)
}

// FindPictures mocks base method.
func (m *MockProfileService) FindPictures(ctx context.Context, userID uuid.UUID) ([]*entity.Picture, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindPictures", ctx, userID)
	ret0, _ := ret[0].([]*entity.Picture)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindPictures indicates an expected call of FindPictures.
func (mr *MockProfileServiceMockRecorder) FindPictures(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindPictures", reflect.TypeOf((*MockProfileService)(nil).FindPictures), ctx, userID)
}

// FindProfile mocks base method.
func (m *MockProfileService) FindProfile(ctx context.Context, userID uuid.UUID) (*entity.UserProfile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindProfile", ctx, userID)
	ret0, _ := ret[0].(*entity.UserProfile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindProfile indicates an expected call of FindProfile.
func (mr *MockProfileServiceMockRecorder) FindProfile(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindProfile", reflect.TypeOf((*MockProfileService)(nil).FindProfile), ctx, userID)
}

// FindWhoLikedMeList mocks base method.
func (m *MockProfileService) FindWhoLikedMeList(ctx context.Context, userID uuid.UUID) ([]*entity.Like, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindWhoLikedMeList", ctx, userID)
	ret0, _ := ret[0].([]*entity.Like)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindWhoLikedMeList indicates an expected call of FindWhoLikedMeList.
func (mr *MockProfileServiceMockRecorder) FindWhoLikedMeList(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindWhoLikedMeList", reflect.TypeOf((*MockProfileService)(nil).FindWhoLikedMeList), ctx, userID)
}

// FindWhoViewedMeList mocks base method.
func (m *MockProfileService) FindWhoViewedMeList(ctx context.Context, userID uuid.UUID) ([]*entity.View, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindWhoViewedMeList", ctx, userID)
	ret0, _ := ret[0].([]*entity.View)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindWhoViewedMeList indicates an expected call of FindWhoViewedMeList.
func (mr *MockProfileServiceMockRecorder) FindWhoViewedMeList(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindWhoViewedMeList", reflect.TypeOf((*MockProfileService)(nil).FindWhoViewedMeList), ctx, userID)
}

// ListProfiles mocks base method.
func (m *MockProfileService) ListProfiles(ctx context.Context, selfUserID uuid.UUID, lat, lon, dist *float64, ageMin, ageMax *int, gender *entity.Gender) ([]*entity.UserProfile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListProfiles", ctx, selfUserID, lat, lon, dist, ageMin, ageMax, gender)
	ret0, _ := ret[0].([]*entity.UserProfile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListProfiles indicates an expected call of ListProfiles.
func (mr *MockProfileServiceMockRecorder) ListProfiles(ctx, selfUserID, lat, lon, dist, ageMin, ageMax, gender any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListProfiles", reflect.TypeOf((*MockProfileService)(nil).ListProfiles), ctx, selfUserID, lat, lon, dist, ageMin, ageMax, gender)
}

// UpdatePictureStatus mocks base method.
func (m *MockProfileService) UpdatePictureStatus(ctx context.Context, userID uuid.UUID, pictureID int32, isProfilePic bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePictureStatus", ctx, userID, pictureID, isProfilePic)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePictureStatus indicates an expected call of UpdatePictureStatus.
func (mr *MockProfileServiceMockRecorder) UpdatePictureStatus(ctx, userID, pictureID, isProfilePic any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePictureStatus", reflect.TypeOf((*MockProfileService)(nil).UpdatePictureStatus), ctx, userID, pictureID, isProfilePic)
}

// UpdateProfile mocks base method.
func (m *MockProfileService) UpdateProfile(ctx context.Context, userID uuid.UUID, profile *entity.UserProfile) (*entity.UserProfile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateProfile", ctx, userID, profile)
	ret0, _ := ret[0].(*entity.UserProfile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateProfile indicates an expected call of UpdateProfile.
func (mr *MockProfileServiceMockRecorder) UpdateProfile(ctx, userID, profile any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProfile", reflect.TypeOf((*MockProfileService)(nil).UpdateProfile), ctx, userID, profile)
}

// UploadPicture mocks base method.
func (m *MockProfileService) UploadPicture(ctx context.Context, userID uuid.UUID, image []byte) (*entity.Picture, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadPicture", ctx, userID, image)
	ret0, _ := ret[0].(*entity.Picture)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UploadPicture indicates an expected call of UploadPicture.
func (mr *MockProfileServiceMockRecorder) UploadPicture(ctx, userID, image any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadPicture", reflect.TypeOf((*MockProfileService)(nil).UploadPicture), ctx, userID, image)
}

// UploadPicutures mocks base method.
func (m *MockProfileService) UploadPicutures(ctx context.Context, userID uuid.UUID, images [][]byte) ([]*entity.Picture, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadPicutures", ctx, userID, images)
	ret0, _ := ret[0].([]*entity.Picture)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UploadPicutures indicates an expected call of UploadPicutures.
func (mr *MockProfileServiceMockRecorder) UploadPicutures(ctx, userID, images any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadPicutures", reflect.TypeOf((*MockProfileService)(nil).UploadPicutures), ctx, userID, images)
}

// ViewProfile mocks base method.
func (m *MockProfileService) ViewProfile(ctx context.Context, viewerID, viewedID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ViewProfile", ctx, viewerID, viewedID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ViewProfile indicates an expected call of ViewProfile.
func (mr *MockProfileServiceMockRecorder) ViewProfile(ctx, viewerID, viewedID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ViewProfile", reflect.TypeOf((*MockProfileService)(nil).ViewProfile), ctx, viewerID, viewedID)
}

// RecommendProfiles mocks base method.
func (m *MockProfileService) RecommendProfiles(ctx context.Context, selfUserID uuid.UUID) ([]*entity.UserProfile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecommendProfiles", ctx, selfUserID)
	ret0, _ := ret[0].([]*entity.UserProfile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RecommendProfiles indicates an expected call of RecommendProfiles.
func (mr *MockProfileServiceMockRecorder) RecommendProfiles(ctx, selfUserID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecommendProfiles", reflect.TypeOf((*MockProfileService)(nil).RecommendProfiles), ctx, selfUserID)
}
