// Code generated by MockGen. DO NOT EDIT.
// Source: domain/repo/refresh_token.go
//
// Generated by this command:
//
//	mockgen -source domain/repo/refresh_token.go -destination mock/refresh_token.go -package mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	entity "github.com/icchon/matcha/api/internal/domain/entity"
	repo "github.com/icchon/matcha/api/internal/domain/repo"
	gomock "go.uber.org/mock/gomock"
)

// MockRefreshTokenQueryRepository is a mock of RefreshTokenQueryRepository interface.
type MockRefreshTokenQueryRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRefreshTokenQueryRepositoryMockRecorder
	isgomock struct{}
}

// MockRefreshTokenQueryRepositoryMockRecorder is the mock recorder for MockRefreshTokenQueryRepository.
type MockRefreshTokenQueryRepositoryMockRecorder struct {
	mock *MockRefreshTokenQueryRepository
}

// NewMockRefreshTokenQueryRepository creates a new mock instance.
func NewMockRefreshTokenQueryRepository(ctrl *gomock.Controller) *MockRefreshTokenQueryRepository {
	mock := &MockRefreshTokenQueryRepository{ctrl: ctrl}
	mock.recorder = &MockRefreshTokenQueryRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRefreshTokenQueryRepository) EXPECT() *MockRefreshTokenQueryRepositoryMockRecorder {
	return m.recorder
}

// Find mocks base method.
func (m *MockRefreshTokenQueryRepository) Find(ctx context.Context, tokenHash string) (*entity.RefreshToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, tokenHash)
	ret0, _ := ret[0].(*entity.RefreshToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockRefreshTokenQueryRepositoryMockRecorder) Find(ctx, tokenHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockRefreshTokenQueryRepository)(nil).Find), ctx, tokenHash)
}

// Query mocks base method.
func (m *MockRefreshTokenQueryRepository) Query(ctx context.Context, q *repo.RefreshTokenQuery) ([]*entity.RefreshToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Query", ctx, q)
	ret0, _ := ret[0].([]*entity.RefreshToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Query indicates an expected call of Query.
func (mr *MockRefreshTokenQueryRepositoryMockRecorder) Query(ctx, q any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Query", reflect.TypeOf((*MockRefreshTokenQueryRepository)(nil).Query), ctx, q)
}

// MockRefreshTokenCommandRepository is a mock of RefreshTokenCommandRepository interface.
type MockRefreshTokenCommandRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRefreshTokenCommandRepositoryMockRecorder
	isgomock struct{}
}

// MockRefreshTokenCommandRepositoryMockRecorder is the mock recorder for MockRefreshTokenCommandRepository.
type MockRefreshTokenCommandRepositoryMockRecorder struct {
	mock *MockRefreshTokenCommandRepository
}

// NewMockRefreshTokenCommandRepository creates a new mock instance.
func NewMockRefreshTokenCommandRepository(ctrl *gomock.Controller) *MockRefreshTokenCommandRepository {
	mock := &MockRefreshTokenCommandRepository{ctrl: ctrl}
	mock.recorder = &MockRefreshTokenCommandRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRefreshTokenCommandRepository) EXPECT() *MockRefreshTokenCommandRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockRefreshTokenCommandRepository) Create(ctx context.Context, token *entity.RefreshToken) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockRefreshTokenCommandRepositoryMockRecorder) Create(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRefreshTokenCommandRepository)(nil).Create), ctx, token)
}

// Delete mocks base method.
func (m *MockRefreshTokenCommandRepository) Delete(ctx context.Context, tokenHash string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, tokenHash)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockRefreshTokenCommandRepositoryMockRecorder) Delete(ctx, tokenHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockRefreshTokenCommandRepository)(nil).Delete), ctx, tokenHash)
}

// Update mocks base method.
func (m *MockRefreshTokenCommandRepository) Update(ctx context.Context, token *entity.RefreshToken) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockRefreshTokenCommandRepositoryMockRecorder) Update(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockRefreshTokenCommandRepository)(nil).Update), ctx, token)
}

// MockRefreshTokenRepository is a mock of RefreshTokenRepository interface.
type MockRefreshTokenRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRefreshTokenRepositoryMockRecorder
	isgomock struct{}
}

// MockRefreshTokenRepositoryMockRecorder is the mock recorder for MockRefreshTokenRepository.
type MockRefreshTokenRepositoryMockRecorder struct {
	mock *MockRefreshTokenRepository
}

// NewMockRefreshTokenRepository creates a new mock instance.
func NewMockRefreshTokenRepository(ctrl *gomock.Controller) *MockRefreshTokenRepository {
	mock := &MockRefreshTokenRepository{ctrl: ctrl}
	mock.recorder = &MockRefreshTokenRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRefreshTokenRepository) EXPECT() *MockRefreshTokenRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockRefreshTokenRepository) Create(ctx context.Context, token *entity.RefreshToken) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockRefreshTokenRepositoryMockRecorder) Create(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRefreshTokenRepository)(nil).Create), ctx, token)
}

// Delete mocks base method.
func (m *MockRefreshTokenRepository) Delete(ctx context.Context, tokenHash string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, tokenHash)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockRefreshTokenRepositoryMockRecorder) Delete(ctx, tokenHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockRefreshTokenRepository)(nil).Delete), ctx, tokenHash)
}

// Find mocks base method.
func (m *MockRefreshTokenRepository) Find(ctx context.Context, tokenHash string) (*entity.RefreshToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, tokenHash)
	ret0, _ := ret[0].(*entity.RefreshToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockRefreshTokenRepositoryMockRecorder) Find(ctx, tokenHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockRefreshTokenRepository)(nil).Find), ctx, tokenHash)
}

// Query mocks base method.
func (m *MockRefreshTokenRepository) Query(ctx context.Context, q *repo.RefreshTokenQuery) ([]*entity.RefreshToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Query", ctx, q)
	ret0, _ := ret[0].([]*entity.RefreshToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Query indicates an expected call of Query.
func (mr *MockRefreshTokenRepositoryMockRecorder) Query(ctx, q any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Query", reflect.TypeOf((*MockRefreshTokenRepository)(nil).Query), ctx, q)
}

// Update mocks base method.
func (m *MockRefreshTokenRepository) Update(ctx context.Context, token *entity.RefreshToken) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockRefreshTokenRepositoryMockRecorder) Update(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockRefreshTokenRepository)(nil).Update), ctx, token)
}
