// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/repo/report.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/repo/report.go -destination=internal/mock/report.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	entity "github.com/icchon/matcha/api/internal/domain/entity"
	repo "github.com/icchon/matcha/api/internal/domain/repo"
	gomock "go.uber.org/mock/gomock"
)

// MockReportQueryRepository is a mock of ReportQueryRepository interface.
type MockReportQueryRepository struct {
	ctrl     *gomock.Controller
	recorder *MockReportQueryRepositoryMockRecorder
	isgomock struct{}
}

// MockReportQueryRepositoryMockRecorder is the mock recorder for MockReportQueryRepository.
type MockReportQueryRepositoryMockRecorder struct {
	mock *MockReportQueryRepository
}

// NewMockReportQueryRepository creates a new mock instance.
func NewMockReportQueryRepository(ctrl *gomock.Controller) *MockReportQueryRepository {
	mock := &MockReportQueryRepository{ctrl: ctrl}
	mock.recorder = &MockReportQueryRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReportQueryRepository) EXPECT() *MockReportQueryRepositoryMockRecorder {
	return m.recorder
}

// Find mocks base method.
func (m *MockReportQueryRepository) Find(ctx context.Context, reportID int64) (*entity.Report, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, reportID)
	ret0, _ := ret[0].(*entity.Report)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockReportQueryRepositoryMockRecorder) Find(ctx, reportID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockReportQueryRepository)(nil).Find), ctx, reportID)
}

// Query mocks base method.
func (m *MockReportQueryRepository) Query(ctx context.Context, q *repo.ReportQuery) ([]*entity.Report, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Query", ctx, q)
	ret0, _ := ret[0].([]*entity.Report)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Query indicates an expected call of Query.
func (mr *MockReportQueryRepositoryMockRecorder) Query(ctx, q any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Query", reflect.TypeOf((*MockReportQueryRepository)(nil).Query), ctx, q)
}

// MockReportCommandRepository is a mock of ReportCommandRepository interface.
type MockReportCommandRepository struct {
	ctrl     *gomock.Controller
	recorder *MockReportCommandRepositoryMockRecorder
	isgomock struct{}
}

// MockReportCommandRepositoryMockRecorder is the mock recorder for MockReportCommandRepository.
type MockReportCommandRepositoryMockRecorder struct {
	mock *MockReportCommandRepository
}

// NewMockReportCommandRepository creates a new mock instance.
func NewMockReportCommandRepository(ctrl *gomock.Controller) *MockReportCommandRepository {
	mock := &MockReportCommandRepository{ctrl: ctrl}
	mock.recorder = &MockReportCommandRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReportCommandRepository) EXPECT() *MockReportCommandRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockReportCommandRepository) Create(ctx context.Context, report *entity.Report) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, report)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockReportCommandRepositoryMockRecorder) Create(ctx, report any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockReportCommandRepository)(nil).Create), ctx, report)
}

// MockReportRepository is a mock of ReportRepository interface.
type MockReportRepository struct {
	ctrl     *gomock.Controller
	recorder *MockReportRepositoryMockRecorder
	isgomock struct{}
}

// MockReportRepositoryMockRecorder is the mock recorder for MockReportRepository.
type MockReportRepositoryMockRecorder struct {
	mock *MockReportRepository
}

// NewMockReportRepository creates a new mock instance.
func NewMockReportRepository(ctrl *gomock.Controller) *MockReportRepository {
	mock := &MockReportRepository{ctrl: ctrl}
	mock.recorder = &MockReportRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReportRepository) EXPECT() *MockReportRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockReportRepository) Create(ctx context.Context, report *entity.Report) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, report)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockReportRepositoryMockRecorder) Create(ctx, report any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockReportRepository)(nil).Create), ctx, report)
}

// Find mocks base method.
func (m *MockReportRepository) Find(ctx context.Context, reportID int64) (*entity.Report, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, reportID)
	ret0, _ := ret[0].(*entity.Report)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockReportRepositoryMockRecorder) Find(ctx, reportID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockReportRepository)(nil).Find), ctx, reportID)
}

// Query mocks base method.
func (m *MockReportRepository) Query(ctx context.Context, q *repo.ReportQuery) ([]*entity.Report, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Query", ctx, q)
	ret0, _ := ret[0].([]*entity.Report)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Query indicates an expected call of Query.
func (mr *MockReportRepositoryMockRecorder) Query(ctx, q any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Query", reflect.TypeOf((*MockReportRepository)(nil).Query), ctx, q)
}
