// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/service/subscriber.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/service/subscriber.go -destination=internal/mock/subscriber_service.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockSubscriberService is a mock of SubscriberService interface.
type MockSubscriberService struct {
	ctrl     *gomock.Controller
	recorder *MockSubscriberServiceMockRecorder
	isgomock struct{}
}

// MockSubscriberServiceMockRecorder is the mock recorder for MockSubscriberService.
type MockSubscriberServiceMockRecorder struct {
	mock *MockSubscriberService
}

// NewMockSubscriberService creates a new mock instance.
func NewMockSubscriberService(ctrl *gomock.Controller) *MockSubscriberService {
	mock := &MockSubscriberService{ctrl: ctrl}
	mock.recorder = &MockSubscriberServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSubscriberService) EXPECT() *MockSubscriberServiceMockRecorder {
	return m.recorder
}

// Initialize mocks base method.
func (m *MockSubscriberService) Initialize(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Initialize", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Initialize indicates an expected call of Initialize.
func (mr *MockSubscriberServiceMockRecorder) Initialize(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Initialize", reflect.TypeOf((*MockSubscriberService)(nil).Initialize), ctx)
}
