// Code generated by MockGen. DO NOT EDIT.
// Source: domain/repo/user_profile.go
//
// Generated by this command:
//
//	mockgen -source domain/repo/user_profile.go -destination mock/user_profile_repo.go -package mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	entity "github.com/icchon/matcha/api/internal/domain/entity"
	repo "github.com/icchon/matcha/api/internal/domain/repo"
	gomock "go.uber.org/mock/gomock"
)

// MockUserProfileQueryRepository is a mock of UserProfileQueryRepository interface.
type MockUserProfileQueryRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserProfileQueryRepositoryMockRecorder
	isgomock struct{}
}

// MockUserProfileQueryRepositoryMockRecorder is the mock recorder for MockUserProfileQueryRepository.
type MockUserProfileQueryRepositoryMockRecorder struct {
	mock *MockUserProfileQueryRepository
}

// NewMockUserProfileQueryRepository creates a new mock instance.
func NewMockUserProfileQueryRepository(ctrl *gomock.Controller) *MockUserProfileQueryRepository {
	mock := &MockUserProfileQueryRepository{ctrl: ctrl}
	mock.recorder = &MockUserProfileQueryRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserProfileQueryRepository) EXPECT() *MockUserProfileQueryRepositoryMockRecorder {
	return m.recorder
}

// Find mocks base method.
func (m *MockUserProfileQueryRepository) Find(ctx context.Context, userID uuid.UUID) (*entity.UserProfile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, userID)
	ret0, _ := ret[0].(*entity.UserProfile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockUserProfileQueryRepositoryMockRecorder) Find(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockUserProfileQueryRepository)(nil).Find), ctx, userID)
}

// Query mocks base method.
func (m *MockUserProfileQueryRepository) Query(ctx context.Context, q *repo.UserProfileQuery) ([]*entity.UserProfile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Query", ctx, q)
	ret0, _ := ret[0].([]*entity.UserProfile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Query indicates an expected call of Query.
func (mr *MockUserProfileQueryRepositoryMockRecorder) Query(ctx, q any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Query", reflect.TypeOf((*MockUserProfileQueryRepository)(nil).Query), ctx, q)
}

// MockUserProfileCommandRepository is a mock of UserProfileCommandRepository interface.
type MockUserProfileCommandRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserProfileCommandRepositoryMockRecorder
	isgomock struct{}
}

// MockUserProfileCommandRepositoryMockRecorder is the mock recorder for MockUserProfileCommandRepository.
type MockUserProfileCommandRepositoryMockRecorder struct {
	mock *MockUserProfileCommandRepository
}

// NewMockUserProfileCommandRepository creates a new mock instance.
func NewMockUserProfileCommandRepository(ctrl *gomock.Controller) *MockUserProfileCommandRepository {
	mock := &MockUserProfileCommandRepository{ctrl: ctrl}
	mock.recorder = &MockUserProfileCommandRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserProfileCommandRepository) EXPECT() *MockUserProfileCommandRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockUserProfileCommandRepository) Create(ctx context.Context, params repo.CreateUserProfileParams) (*entity.UserProfile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, params)
	ret0, _ := ret[0].(*entity.UserProfile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockUserProfileCommandRepositoryMockRecorder) Create(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockUserProfileCommandRepository)(nil).Create), ctx, params)
}

// Delete mocks base method.
func (m *MockUserProfileCommandRepository) Delete(ctx context.Context, userID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockUserProfileCommandRepositoryMockRecorder) Delete(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockUserProfileCommandRepository)(nil).Delete), ctx, userID)
}

// Update mocks base method.
func (m *MockUserProfileCommandRepository) Update(ctx context.Context, userProfile *entity.UserProfile) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, userProfile)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockUserProfileCommandRepositoryMockRecorder) Update(ctx, userProfile any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockUserProfileCommandRepository)(nil).Update), ctx, userProfile)
}

// MockUserProfileRepository is a mock of UserProfileRepository interface.
type MockUserProfileRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserProfileRepositoryMockRecorder
	isgomock struct{}
}

// MockUserProfileRepositoryMockRecorder is the mock recorder for MockUserProfileRepository.
type MockUserProfileRepositoryMockRecorder struct {
	mock *MockUserProfileRepository
}

// NewMockUserProfileRepository creates a new mock instance.
func NewMockUserProfileRepository(ctrl *gomock.Controller) *MockUserProfileRepository {
	mock := &MockUserProfileRepository{ctrl: ctrl}
	mock.recorder = &MockUserProfileRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserProfileRepository) EXPECT() *MockUserProfileRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockUserProfileRepository) Create(ctx context.Context, params repo.CreateUserProfileParams) (*entity.UserProfile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, params)
	ret0, _ := ret[0].(*entity.UserProfile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockUserProfileRepositoryMockRecorder) Create(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockUserProfileRepository)(nil).Create), ctx, params)
}

// Delete mocks base method.
func (m *MockUserProfileRepository) Delete(ctx context.Context, userID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockUserProfileRepositoryMockRecorder) Delete(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockUserProfileRepository)(nil).Delete), ctx, userID)
}

// Find mocks base method.
func (m *MockUserProfileRepository) Find(ctx context.Context, userID uuid.UUID) (*entity.UserProfile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, userID)
	ret0, _ := ret[0].(*entity.UserProfile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockUserProfileRepositoryMockRecorder) Find(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockUserProfileRepository)(nil).Find), ctx, userID)
}

// Query mocks base method.
func (m *MockUserProfileRepository) Query(ctx context.Context, q *repo.UserProfileQuery) ([]*entity.UserProfile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Query", ctx, q)
	ret0, _ := ret[0].([]*entity.UserProfile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Query indicates an expected call of Query.
func (mr *MockUserProfileRepositoryMockRecorder) Query(ctx, q any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Query", reflect.TypeOf((*MockUserProfileRepository)(nil).Query), ctx, q)
}

// Update mocks base method.
func (m *MockUserProfileRepository) Update(ctx context.Context, userProfile *entity.UserProfile) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, userProfile)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockUserProfileRepositoryMockRecorder) Update(ctx, userProfile any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockUserProfileRepository)(nil).Update), ctx, userProfile)
}
