// Code generated by MockGen. DO NOT EDIT.
// Source: domain/repo/user_tag.go
//
// Generated by this command:
//
//	mockgen -source domain/repo/user_tag.go -destination mock/user_tag.go -package mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	entity "github.com/icchon/matcha/api/internal/domain/entity"
	repo "github.com/icchon/matcha/api/internal/domain/repo"
	gomock "go.uber.org/mock/gomock"
)

// MockUserTagQueryRepository is a mock of UserTagQueryRepository interface.
type MockUserTagQueryRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserTagQueryRepositoryMockRecorder
	isgomock struct{}
}

// MockUserTagQueryRepositoryMockRecorder is the mock recorder for MockUserTagQueryRepository.
type MockUserTagQueryRepositoryMockRecorder struct {
	mock *MockUserTagQueryRepository
}

// NewMockUserTagQueryRepository creates a new mock instance.
func NewMockUserTagQueryRepository(ctrl *gomock.Controller) *MockUserTagQueryRepository {
	mock := &MockUserTagQueryRepository{ctrl: ctrl}
	mock.recorder = &MockUserTagQueryRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserTagQueryRepository) EXPECT() *MockUserTagQueryRepositoryMockRecorder {
	return m.recorder
}

// Query mocks base method.
func (m *MockUserTagQueryRepository) Query(ctx context.Context, q *repo.UserTagQuery) ([]*entity.Tag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Query", ctx, q)
	ret0, _ := ret[0].([]*entity.Tag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Query indicates an expected call of Query.
func (mr *MockUserTagQueryRepositoryMockRecorder) Query(ctx, q any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Query", reflect.TypeOf((*MockUserTagQueryRepository)(nil).Query), ctx, q)
}

// MockUserTagCommandRepository is a mock of UserTagCommandRepository interface.
type MockUserTagCommandRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserTagCommandRepositoryMockRecorder
	isgomock struct{}
}

// MockUserTagCommandRepositoryMockRecorder is the mock recorder for MockUserTagCommandRepository.
type MockUserTagCommandRepositoryMockRecorder struct {
	mock *MockUserTagCommandRepository
}

// NewMockUserTagCommandRepository creates a new mock instance.
func NewMockUserTagCommandRepository(ctrl *gomock.Controller) *MockUserTagCommandRepository {
	mock := &MockUserTagCommandRepository{ctrl: ctrl}
	mock.recorder = &MockUserTagCommandRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserTagCommandRepository) EXPECT() *MockUserTagCommandRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockUserTagCommandRepository) Create(ctx context.Context, userTag *entity.UserTag) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, userTag)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockUserTagCommandRepositoryMockRecorder) Create(ctx, userTag any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockUserTagCommandRepository)(nil).Create), ctx, userTag)
}

// Delete mocks base method.
func (m *MockUserTagCommandRepository) Delete(ctx context.Context, userID uuid.UUID, tagID int32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, userID, tagID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockUserTagCommandRepositoryMockRecorder) Delete(ctx, userID, tagID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockUserTagCommandRepository)(nil).Delete), ctx, userID, tagID)
}

// MockUserTagRepository is a mock of UserTagRepository interface.
type MockUserTagRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserTagRepositoryMockRecorder
	isgomock struct{}
}

// MockUserTagRepositoryMockRecorder is the mock recorder for MockUserTagRepository.
type MockUserTagRepositoryMockRecorder struct {
	mock *MockUserTagRepository
}

// NewMockUserTagRepository creates a new mock instance.
func NewMockUserTagRepository(ctrl *gomock.Controller) *MockUserTagRepository {
	mock := &MockUserTagRepository{ctrl: ctrl}
	mock.recorder = &MockUserTagRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserTagRepository) EXPECT() *MockUserTagRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockUserTagRepository) Create(ctx context.Context, userTag *entity.UserTag) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, userTag)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockUserTagRepositoryMockRecorder) Create(ctx, userTag any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockUserTagRepository)(nil).Create), ctx, userTag)
}

// Delete mocks base method.
func (m *MockUserTagRepository) Delete(ctx context.Context, userID uuid.UUID, tagID int32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, userID, tagID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockUserTagRepositoryMockRecorder) Delete(ctx, userID, tagID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockUserTagRepository)(nil).Delete), ctx, userID, tagID)
}

// Query mocks base method.
func (m *MockUserTagRepository) Query(ctx context.Context, q *repo.UserTagQuery) ([]*entity.Tag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Query", ctx, q)
	ret0, _ := ret[0].([]*entity.Tag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Query indicates an expected call of Query.
func (mr *MockUserTagRepositoryMockRecorder) Query(ctx, q any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Query", reflect.TypeOf((*MockUserTagRepository)(nil).Query), ctx, q)
}
