// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/service/user.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/service/user.go -destination=internal/mock/user_service.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	entity "github.com/icchon/matcha/api/internal/domain/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockUserService is a mock of UserService interface.
type MockUserService struct {
	ctrl     *gomock.Controller
	recorder *MockUserServiceMockRecorder
	isgomock struct{}
}

// MockUserServiceMockRecorder is the mock recorder for MockUserService.
type MockUserServiceMockRecorder struct {
	mock *MockUserService
}

// NewMockUserService creates a new mock instance.
func NewMockUserService(ctrl *gomock.Controller) *MockUserService {
	mock := &MockUserService{ctrl: ctrl}
	mock.recorder = &MockUserServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserService) EXPECT() *MockUserServiceMockRecorder {
	return m.recorder
}

// AddUserTag mocks base method.
func (m *MockUserService) AddUserTag(ctx context.Context, userID uuid.UUID, tagID int32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddUserTag", ctx, userID, tagID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddUserTag indicates an expected call of AddUserTag.
func (mr *MockUserServiceMockRecorder) AddUserTag(ctx, userID, tagID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddUserTag", reflect.TypeOf((*MockUserService)(nil).AddUserTag), ctx, userID, tagID)
}

// BlockUser mocks base method.
func (m *MockUserService) BlockUser(ctx context.Context, blockerID, blockedID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BlockUser", ctx, blockerID, blockedID)
	ret0, _ := ret[0].(error)
	return ret0
}

// BlockUser indicates an expected call of BlockUser.
func (mr *MockUserServiceMockRecorder) BlockUser(ctx, blockerID, blockedID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BlockUser", reflect.TypeOf((*MockUserService)(nil).BlockUser), ctx, blockerID, blockedID)
}

// CreateUserData mocks base method.
func (m *MockUserService) CreateUserData(ctx context.Context, userData *entity.UserData) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUserData", ctx, userData)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateUserData indicates an expected call of CreateUserData.
func (mr *MockUserServiceMockRecorder) CreateUserData(ctx, userData any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUserData", reflect.TypeOf((*MockUserService)(nil).CreateUserData), ctx, userData)
}

// DeleteUser mocks base method.
func (m *MockUserService) DeleteUser(ctx context.Context, userID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUser", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUser indicates an expected call of DeleteUser.
func (mr *MockUserServiceMockRecorder) DeleteUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUser", reflect.TypeOf((*MockUserService)(nil).DeleteUser), ctx, userID)
}

// DeleteUserTag mocks base method.
func (m *MockUserService) DeleteUserTag(ctx context.Context, userID uuid.UUID, tagID int32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUserTag", ctx, userID, tagID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUserTag indicates an expected call of DeleteUserTag.
func (mr *MockUserServiceMockRecorder) DeleteUserTag(ctx, userID, tagID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUserTag", reflect.TypeOf((*MockUserService)(nil).DeleteUserTag), ctx, userID, tagID)
}

// FindBlockList mocks base method.
func (m *MockUserService) FindBlockList(ctx context.Context, userID uuid.UUID) ([]*entity.Block, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindBlockList", ctx, userID)
	ret0, _ := ret[0].([]*entity.Block)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindBlockList indicates an expected call of FindBlockList.
func (mr *MockUserServiceMockRecorder) FindBlockList(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindBlockList", reflect.TypeOf((*MockUserService)(nil).FindBlockList), ctx, userID)
}

// FindConnections mocks base method.
func (m *MockUserService) FindConnections(ctx context.Context, userID uuid.UUID) ([]*entity.Connection, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindConnections", ctx, userID)
	ret0, _ := ret[0].([]*entity.Connection)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindConnections indicates an expected call of FindConnections.
func (mr *MockUserServiceMockRecorder) FindConnections(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindConnections", reflect.TypeOf((*MockUserService)(nil).FindConnections), ctx, userID)
}

// FindMyLikedList mocks base method.
func (m *MockUserService) FindMyLikedList(ctx context.Context, userID uuid.UUID) ([]*entity.Like, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindMyLikedList", ctx, userID)
	ret0, _ := ret[0].([]*entity.Like)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindMyLikedList indicates an expected call of FindMyLikedList.
func (mr *MockUserServiceMockRecorder) FindMyLikedList(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindMyLikedList", reflect.TypeOf((*MockUserService)(nil).FindMyLikedList), ctx, userID)
}

// FindMyViewedList mocks base method.
func (m *MockUserService) FindMyViewedList(ctx context.Context, userID uuid.UUID) ([]*entity.View, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindMyViewedList", ctx, userID)
	ret0, _ := ret[0].([]*entity.View)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindMyViewedList indicates an expected call of FindMyViewedList.
func (mr *MockUserServiceMockRecorder) FindMyViewedList(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindMyViewedList", reflect.TypeOf((*MockUserService)(nil).FindMyViewedList), ctx, userID)
}

// GetAllTags mocks base method.
func (m *MockUserService) GetAllTags(ctx context.Context) ([]*entity.Tag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllTags", ctx)
	ret0, _ := ret[0].([]*entity.Tag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllTags indicates an expected call of GetAllTags.
func (mr *MockUserServiceMockRecorder) GetAllTags(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllTags", reflect.TypeOf((*MockUserService)(nil).GetAllTags), ctx)
}

// GetUserData mocks base method.
func (m *MockUserService) GetUserData(ctx context.Context, userID uuid.UUID) (*entity.UserData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserData", ctx, userID)
	ret0, _ := ret[0].(*entity.UserData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserData indicates an expected call of GetUserData.
func (mr *MockUserServiceMockRecorder) GetUserData(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserData", reflect.TypeOf((*MockUserService)(nil).GetUserData), ctx, userID)
}

// GetUserTags mocks base method.
func (m *MockUserService) GetUserTags(ctx context.Context, userID uuid.UUID) ([]*entity.Tag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserTags", ctx, userID)
	ret0, _ := ret[0].([]*entity.Tag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserTags indicates an expected call of GetUserTags.
func (mr *MockUserServiceMockRecorder) GetUserTags(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserTags", reflect.TypeOf((*MockUserService)(nil).GetUserTags), ctx, userID)
}

// LikeUser mocks base method.
func (m *MockUserService) LikeUser(ctx context.Context, likerID, likedID uuid.UUID) (*entity.Connection, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LikeUser", ctx, likerID, likedID)
	ret0, _ := ret[0].(*entity.Connection)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LikeUser indicates an expected call of LikeUser.
func (mr *MockUserServiceMockRecorder) LikeUser(ctx, likerID, likedID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LikeUser", reflect.TypeOf((*MockUserService)(nil).LikeUser), ctx, likerID, likedID)
}

// ReportUser mocks base method.
func (m *MockUserService) ReportUser(ctx context.Context, reporterID, reportedID uuid.UUID, reason string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReportUser", ctx, reporterID, reportedID, reason)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReportUser indicates an expected call of ReportUser.
func (mr *MockUserServiceMockRecorder) ReportUser(ctx, reporterID, reportedID, reason any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReportUser", reflect.TypeOf((*MockUserService)(nil).ReportUser), ctx, reporterID, reportedID, reason)
}

// UnblockUser mocks base method.
func (m *MockUserService) UnblockUser(ctx context.Context, blockerID, blockedID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnblockUser", ctx, blockerID, blockedID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnblockUser indicates an expected call of UnblockUser.
func (mr *MockUserServiceMockRecorder) UnblockUser(ctx, blockerID, blockedID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnblockUser", reflect.TypeOf((*MockUserService)(nil).UnblockUser), ctx, blockerID, blockedID)
}

// UnlikeUser mocks base method.
func (m *MockUserService) UnlikeUser(ctx context.Context, likerID, likedID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnlikeUser", ctx, likerID, likedID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnlikeUser indicates an expected call of UnlikeUser.
func (mr *MockUserServiceMockRecorder) UnlikeUser(ctx, likerID, likedID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnlikeUser", reflect.TypeOf((*MockUserService)(nil).UnlikeUser), ctx, likerID, likedID)
}

// UpdateUserData mocks base method.
func (m *MockUserService) UpdateUserData(ctx context.Context, userData *entity.UserData) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserData", ctx, userData)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUserData indicates an expected call of UpdateUserData.
func (mr *MockUserServiceMockRecorder) UpdateUserData(ctx, userData any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserData", reflect.TypeOf((*MockUserService)(nil).UpdateUserData), ctx, userData)
}
