// Code generated by MockGen. DO NOT EDIT.
// Source: domain/repo/user_data.go
//
// Generated by this command:
//
//	mockgen -source domain/repo/user_data.go -destination mock/user_data_repo.go -package mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	entity "github.com/icchon/matcha/api/internal/domain/entity"
	repo "github.com/icchon/matcha/api/internal/domain/repo"
	gomock "go.uber.org/mock/gomock"
)

// MockUserDataQueryRepository is a mock of UserDataQueryRepository interface.
type MockUserDataQueryRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserDataQueryRepositoryMockRecorder
	isgomock struct{}
}

// MockUserDataQueryRepositoryMockRecorder is the mock recorder for MockUserDataQueryRepository.
type MockUserDataQueryRepositoryMockRecorder struct {
	mock *MockUserDataQueryRepository
}

// NewMockUserDataQueryRepository creates a new mock instance.
func NewMockUserDataQueryRepository(ctrl *gomock.Controller) *MockUserDataQueryRepository {
	mock := &MockUserDataQueryRepository{ctrl: ctrl}
	mock.recorder = &MockUserDataQueryRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserDataQueryRepository) EXPECT() *MockUserDataQueryRepositoryMockRecorder {
	return m.recorder
}

// Find mocks base method.
func (m *MockUserDataQueryRepository) Find(ctx context.Context, userID uuid.UUID) (*entity.UserData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, userID)
	ret0, _ := ret[0].(*entity.UserData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockUserDataQueryRepositoryMockRecorder) Find(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockUserDataQueryRepository)(nil).Find), ctx, userID)
}

// Query mocks base method.
func (m *MockUserDataQueryRepository) Query(ctx context.Context, q *repo.UserDataQuery) ([]*entity.UserData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Query", ctx, q)
	ret0, _ := ret[0].([]*entity.UserData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Query indicates an expected call of Query.
func (mr *MockUserDataQueryRepositoryMockRecorder) Query(ctx, q any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Query", reflect.TypeOf((*MockUserDataQueryRepository)(nil).Query), ctx, q)
}

// MockUserDataCommandRepository is a mock of UserDataCommandRepository interface.
type MockUserDataCommandRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserDataCommandRepositoryMockRecorder
	isgomock struct{}
}

// MockUserDataCommandRepositoryMockRecorder is the mock recorder for MockUserDataCommandRepository.
type MockUserDataCommandRepositoryMockRecorder struct {
	mock *MockUserDataCommandRepository
}

// NewMockUserDataCommandRepository creates a new mock instance.
func NewMockUserDataCommandRepository(ctrl *gomock.Controller) *MockUserDataCommandRepository {
	mock := &MockUserDataCommandRepository{ctrl: ctrl}
	mock.recorder = &MockUserDataCommandRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserDataCommandRepository) EXPECT() *MockUserDataCommandRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockUserDataCommandRepository) Create(ctx context.Context, params repo.CreateUserDataParams) (*entity.UserData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, params)
	ret0, _ := ret[0].(*entity.UserData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockUserDataCommandRepositoryMockRecorder) Create(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockUserDataCommandRepository)(nil).Create), ctx, params)
}

// Delete mocks base method.
func (m *MockUserDataCommandRepository) Delete(ctx context.Context, userID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockUserDataCommandRepositoryMockRecorder) Delete(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockUserDataCommandRepository)(nil).Delete), ctx, userID)
}

// Update mocks base method.
func (m *MockUserDataCommandRepository) Update(ctx context.Context, userData *entity.UserData) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, userData)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockUserDataCommandRepositoryMockRecorder) Update(ctx, userData any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockUserDataCommandRepository)(nil).Update), ctx, userData)
}

// MockUserDataRepository is a mock of UserDataRepository interface.
type MockUserDataRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserDataRepositoryMockRecorder
	isgomock struct{}
}

// MockUserDataRepositoryMockRecorder is the mock recorder for MockUserDataRepository.
type MockUserDataRepositoryMockRecorder struct {
	mock *MockUserDataRepository
}

// NewMockUserDataRepository creates a new mock instance.
func NewMockUserDataRepository(ctrl *gomock.Controller) *MockUserDataRepository {
	mock := &MockUserDataRepository{ctrl: ctrl}
	mock.recorder = &MockUserDataRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserDataRepository) EXPECT() *MockUserDataRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockUserDataRepository) Create(ctx context.Context, params repo.CreateUserDataParams) (*entity.UserData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, params)
	ret0, _ := ret[0].(*entity.UserData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockUserDataRepositoryMockRecorder) Create(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockUserDataRepository)(nil).Create), ctx, params)
}

// Delete mocks base method.
func (m *MockUserDataRepository) Delete(ctx context.Context, userID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockUserDataRepositoryMockRecorder) Delete(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockUserDataRepository)(nil).Delete), ctx, userID)
}

// Find mocks base method.
func (m *MockUserDataRepository) Find(ctx context.Context, userID uuid.UUID) (*entity.UserData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, userID)
	ret0, _ := ret[0].(*entity.UserData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockUserDataRepositoryMockRecorder) Find(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockUserDataRepository)(nil).Find), ctx, userID)
}

// Query mocks base method.
func (m *MockUserDataRepository) Query(ctx context.Context, q *repo.UserDataQuery) ([]*entity.UserData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Query", ctx, q)
	ret0, _ := ret[0].([]*entity.UserData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Query indicates an expected call of Query.
func (mr *MockUserDataRepositoryMockRecorder) Query(ctx, q any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Query", reflect.TypeOf((*MockUserDataRepository)(nil).Query), ctx, q)
}

// Update mocks base method.
func (m *MockUserDataRepository) Update(ctx context.Context, userData *entity.UserData) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, userData)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockUserDataRepositoryMockRecorder) Update(ctx, userData any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockUserDataRepository)(nil).Update), ctx, userData)
}
