// Code generated by MockGen. DO NOT EDIT.
// Source: domain/repo/verification_token.go
//
// Generated by this command:
//
//	mockgen -source domain/repo/verification_token.go -destination mock/verification_token_repo.go -package mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	entity "github.com/icchon/matcha/api/internal/domain/entity"
	repo "github.com/icchon/matcha/api/internal/domain/repo"
	gomock "go.uber.org/mock/gomock"
)

// MockVerificationTokenQueryRepository is a mock of VerificationTokenQueryRepository interface.
type MockVerificationTokenQueryRepository struct {
	ctrl     *gomock.Controller
	recorder *MockVerificationTokenQueryRepositoryMockRecorder
	isgomock struct{}
}

// MockVerificationTokenQueryRepositoryMockRecorder is the mock recorder for MockVerificationTokenQueryRepository.
type MockVerificationTokenQueryRepositoryMockRecorder struct {
	mock *MockVerificationTokenQueryRepository
}

// NewMockVerificationTokenQueryRepository creates a new mock instance.
func NewMockVerificationTokenQueryRepository(ctrl *gomock.Controller) *MockVerificationTokenQueryRepository {
	mock := &MockVerificationTokenQueryRepository{ctrl: ctrl}
	mock.recorder = &MockVerificationTokenQueryRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVerificationTokenQueryRepository) EXPECT() *MockVerificationTokenQueryRepositoryMockRecorder {
	return m.recorder
}

// Find mocks base method.
func (m *MockVerificationTokenQueryRepository) Find(ctx context.Context, token string) (*entity.VerificationToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, token)
	ret0, _ := ret[0].(*entity.VerificationToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockVerificationTokenQueryRepositoryMockRecorder) Find(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockVerificationTokenQueryRepository)(nil).Find), ctx, token)
}

// Query mocks base method.
func (m *MockVerificationTokenQueryRepository) Query(ctx context.Context, q *repo.VerificationTokenQuery) ([]*entity.VerificationToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Query", ctx, q)
	ret0, _ := ret[0].([]*entity.VerificationToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Query indicates an expected call of Query.
func (mr *MockVerificationTokenQueryRepositoryMockRecorder) Query(ctx, q any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Query", reflect.TypeOf((*MockVerificationTokenQueryRepository)(nil).Query), ctx, q)
}

// MockVerificationTokenCommandRepository is a mock of VerificationTokenCommandRepository interface.
type MockVerificationTokenCommandRepository struct {
	ctrl     *gomock.Controller
	recorder *MockVerificationTokenCommandRepositoryMockRecorder
	isgomock struct{}
}

// MockVerificationTokenCommandRepositoryMockRecorder is the mock recorder for MockVerificationTokenCommandRepository.
type MockVerificationTokenCommandRepositoryMockRecorder struct {
	mock *MockVerificationTokenCommandRepository
}

// NewMockVerificationTokenCommandRepository creates a new mock instance.
func NewMockVerificationTokenCommandRepository(ctrl *gomock.Controller) *MockVerificationTokenCommandRepository {
	mock := &MockVerificationTokenCommandRepository{ctrl: ctrl}
	mock.recorder = &MockVerificationTokenCommandRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVerificationTokenCommandRepository) EXPECT() *MockVerificationTokenCommandRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockVerificationTokenCommandRepository) Create(ctx context.Context, params repo.CreateVerificationTokenParams) (*entity.VerificationToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, params)
	ret0, _ := ret[0].(*entity.VerificationToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockVerificationTokenCommandRepositoryMockRecorder) Create(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockVerificationTokenCommandRepository)(nil).Create), ctx, params)
}

// Delete mocks base method.
func (m *MockVerificationTokenCommandRepository) Delete(ctx context.Context, token string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockVerificationTokenCommandRepositoryMockRecorder) Delete(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockVerificationTokenCommandRepository)(nil).Delete), ctx, token)
}

// Update mocks base method.
func (m *MockVerificationTokenCommandRepository) Update(ctx context.Context, token *entity.VerificationToken) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockVerificationTokenCommandRepositoryMockRecorder) Update(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockVerificationTokenCommandRepository)(nil).Update), ctx, token)
}

// MockVerificationTokenRepository is a mock of VerificationTokenRepository interface.
type MockVerificationTokenRepository struct {
	ctrl     *gomock.Controller
	recorder *MockVerificationTokenRepositoryMockRecorder
	isgomock struct{}
}

// MockVerificationTokenRepositoryMockRecorder is the mock recorder for MockVerificationTokenRepository.
type MockVerificationTokenRepositoryMockRecorder struct {
	mock *MockVerificationTokenRepository
}

// NewMockVerificationTokenRepository creates a new mock instance.
func NewMockVerificationTokenRepository(ctrl *gomock.Controller) *MockVerificationTokenRepository {
	mock := &MockVerificationTokenRepository{ctrl: ctrl}
	mock.recorder = &MockVerificationTokenRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVerificationTokenRepository) EXPECT() *MockVerificationTokenRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockVerificationTokenRepository) Create(ctx context.Context, params repo.CreateVerificationTokenParams) (*entity.VerificationToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, params)
	ret0, _ := ret[0].(*entity.VerificationToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockVerificationTokenRepositoryMockRecorder) Create(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockVerificationTokenRepository)(nil).Create), ctx, params)
}

// Delete mocks base method.
func (m *MockVerificationTokenRepository) Delete(ctx context.Context, token string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockVerificationTokenRepositoryMockRecorder) Delete(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockVerificationTokenRepository)(nil).Delete), ctx, token)
}

// Find mocks base method.
func (m *MockVerificationTokenRepository) Find(ctx context.Context, token string) (*entity.VerificationToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, token)
	ret0, _ := ret[0].(*entity.VerificationToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockVerificationTokenRepositoryMockRecorder) Find(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockVerificationTokenRepository)(nil).Find), ctx, token)
}

// Query mocks base method.
func (m *MockVerificationTokenRepository) Query(ctx context.Context, q *repo.VerificationTokenQuery) ([]*entity.VerificationToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Query", ctx, q)
	ret0, _ := ret[0].([]*entity.VerificationToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Query indicates an expected call of Query.
func (mr *MockVerificationTokenRepositoryMockRecorder) Query(ctx, q any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Query", reflect.TypeOf((*MockVerificationTokenRepository)(nil).Query), ctx, q)
}

// Update mocks base method.
func (m *MockVerificationTokenRepository) Update(ctx context.Context, token *entity.VerificationToken) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockVerificationTokenRepositoryMockRecorder) Update(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockVerificationTokenRepository)(nil).Update), ctx, token)
}
