// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/repo/view.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/repo/view.go -destination=internal/mock/view.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	entity "github.com/icchon/matcha/api/internal/domain/entity"
	repo "github.com/icchon/matcha/api/internal/domain/repo"
	gomock "go.uber.org/mock/gomock"
)

// MockViewQueryRepository is a mock of ViewQueryRepository interface.
type MockViewQueryRepository struct {
	ctrl     *gomock.Controller
	recorder *MockViewQueryRepositoryMockRecorder
	isgomock struct{}
}

// MockViewQueryRepositoryMockRecorder is the mock recorder for MockViewQueryRepository.
type MockViewQueryRepositoryMockRecorder struct {
	mock *MockViewQueryRepository
}

// NewMockViewQueryRepository creates a new mock instance.
func NewMockViewQueryRepository(ctrl *gomock.Controller) *MockViewQueryRepository {
	mock := &MockViewQueryRepository{ctrl: ctrl}
	mock.recorder = &MockViewQueryRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockViewQueryRepository) EXPECT() *MockViewQueryRepositoryMockRecorder {
	return m.recorder
}

// Find mocks base method.
func (m *MockViewQueryRepository) Find(ctx context.Context, viewerID, viewedID uuid.UUID) (*entity.View, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, viewerID, viewedID)
	ret0, _ := ret[0].(*entity.View)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockViewQueryRepositoryMockRecorder) Find(ctx, viewerID, viewedID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockViewQueryRepository)(nil).Find), ctx, viewerID, viewedID)
}

// Query mocks base method.
func (m *MockViewQueryRepository) Query(ctx context.Context, q *repo.ViewQuery) ([]*entity.View, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Query", ctx, q)
	ret0, _ := ret[0].([]*entity.View)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Query indicates an expected call of Query.
func (mr *MockViewQueryRepositoryMockRecorder) Query(ctx, q any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Query", reflect.TypeOf((*MockViewQueryRepository)(nil).Query), ctx, q)
}

// MockViewCommandRepository is a mock of ViewCommandRepository interface.
type MockViewCommandRepository struct {
	ctrl     *gomock.Controller
	recorder *MockViewCommandRepositoryMockRecorder
	isgomock struct{}
}

// MockViewCommandRepositoryMockRecorder is the mock recorder for MockViewCommandRepository.
type MockViewCommandRepositoryMockRecorder struct {
	mock *MockViewCommandRepository
}

// NewMockViewCommandRepository creates a new mock instance.
func NewMockViewCommandRepository(ctrl *gomock.Controller) *MockViewCommandRepository {
	mock := &MockViewCommandRepository{ctrl: ctrl}
	mock.recorder = &MockViewCommandRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockViewCommandRepository) EXPECT() *MockViewCommandRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockViewCommandRepository) Create(ctx context.Context, view *entity.View) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, view)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockViewCommandRepositoryMockRecorder) Create(ctx, view any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockViewCommandRepository)(nil).Create), ctx, view)
}

// Delete mocks base method.
func (m *MockViewCommandRepository) Delete(ctx context.Context, viewerID, viewedID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, viewerID, viewedID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockViewCommandRepositoryMockRecorder) Delete(ctx, viewerID, viewedID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockViewCommandRepository)(nil).Delete), ctx, viewerID, viewedID)
}

// MockViewRepository is a mock of ViewRepository interface.
type MockViewRepository struct {
	ctrl     *gomock.Controller
	recorder *MockViewRepositoryMockRecorder
	isgomock struct{}
}

// MockViewRepositoryMockRecorder is the mock recorder for MockViewRepository.
type MockViewRepositoryMockRecorder struct {
	mock *MockViewRepository
}

// NewMockViewRepository creates a new mock instance.
func NewMockViewRepository(ctrl *gomock.Controller) *MockViewRepository {
	mock := &MockViewRepository{ctrl: ctrl}
	mock.recorder = &MockViewRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockViewRepository) EXPECT() *MockViewRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockViewRepository) Create(ctx context.Context, view *entity.View) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, view)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockViewRepositoryMockRecorder) Create(ctx, view any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockViewRepository)(nil).Create), ctx, view)
}

// Delete mocks base method.
func (m *MockViewRepository) Delete(ctx context.Context, viewerID, viewedID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, viewerID, viewedID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockViewRepositoryMockRecorder) Delete(ctx, viewerID, viewedID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockViewRepository)(nil).Delete), ctx, viewerID, viewedID)
}

// Find mocks base method.
func (m *MockViewRepository) Find(ctx context.Context, viewerID, viewedID uuid.UUID) (*entity.View, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, viewerID, viewedID)
	ret0, _ := ret[0].(*entity.View)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockViewRepositoryMockRecorder) Find(ctx, viewerID, viewedID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockViewRepository)(nil).Find), ctx, viewerID, viewedID)
}

// Query mocks base method.
func (m *MockViewRepository) Query(ctx context.Context, q *repo.ViewQuery) ([]*entity.View, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Query", ctx, q)
	ret0, _ := ret[0].([]*entity.View)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Query indicates an expected call of Query.
func (mr *MockViewRepositoryMockRecorder) Query(ctx, q any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Query", reflect.TypeOf((*MockViewRepository)(nil).Query), ctx, q)
}
